Imports System.IO

Public Class ArchiveFiles

    Sub New()

        InitializeComponent()
        ' This line of code is generated by Data Source Configuration Wizard
        ' Fill a SqlDataSource
        SqlDataSource1.Fill()
        ' This line of code is generated by Data Source Configuration Wizard
        ' Fill a SqlDataSource
        SqlDataSource1.Fill()
        ' This line of code is generated by Data Source Configuration Wizard
        ' Fill a SqlDataSource
        SqlDataSource1.Fill()
    End Sub

    Private Sub ArchiveFiles_Load(sender As Object, e As EventArgs) Handles MyBase.Load
        'TODO: This line of code loads data into the 'WizCountDataSet.Accounts1' table. You can move, or remove it, as needed.
        ' Me.Accounts1TableAdapter.Fill(Me.WizCountDataSet.Accounts1)

    End Sub

    Dim loadDrives As Boolean = False

    Private Sub Form1_Load(ByVal sender As System.Object,
    ByVal e As System.EventArgs) Handles MyBase.Load
        TreeList1.DataSource = New Object()
    End Sub

    Function IsFile(ByVal info As DirectoryInfo) As Boolean
        Return (info.Attributes And FileAttributes.Directory) = 0
    End Function

    Private Sub TreeList1_VirtualTreeGetCellValue(ByVal sender As Object,
    ByVal e As DevExpress.XtraTreeList.VirtualTreeGetCellValueInfo) _
    Handles TreeList1.VirtualTreeGetCellValue
        Dim di As New DirectoryInfo(CStr(e.Node))
        If e.Column Is TreeListColumn1 Then
            e.CellData = di.Name
        End If
        If e.Column Is TreeListColumn2 Then
            If Not IsFile(di) Then
                e.CellData = "Folder"
            Else
                e.CellData = "File"
            End If
        End If
        If e.Column Is TreeListColumn3 Then
            If IsFile(di) Then
                e.CellData = New FileInfo(CStr(e.Node)).Length
            Else
                e.CellData = Nothing
            End If
        End If
    End Sub

    Private Sub TreeList1_VirtualTreeGetChildNodes(ByVal sender As Object,
    ByVal e As DevExpress.XtraTreeList.VirtualTreeGetChildNodesInfo) _
    Handles TreeList1.VirtualTreeGetChildNodes
        If loadDrives = False Then
            Dim root As String() = Directory.GetLogicalDrives()
            e.Children = root
            loadDrives = True
        Else
            Try
                Dim path As String = CStr(e.Node)
                If Directory.Exists(path) Then
                    Dim dirs As String() = Directory.GetDirectories(path)
                    Dim files As String() = Directory.GetFiles(path)
                    Dim arr(dirs.Length + files.Length) As String
                    dirs.CopyTo(arr, 0)
                    files.CopyTo(arr, dirs.Length)
                    e.Children = arr
                Else
                    e.Children = New Object() {}
                End If
            Catch
            End Try
        End If
    End Sub

    Private Sub TreeList1_VirtualTreeSetCellValue(ByVal sender As System.Object,
    ByVal e As DevExpress.XtraTreeList.VirtualTreeSetCellValueInfo) _
    Handles TreeList1.VirtualTreeSetCellValue
        '...
    End Sub

End Class