Public Class Employee

    Sub New()

        InitializeComponent()
        ' This line of code is generated by Data Source Configuration Wizard
        '   EmployeesDataTableAdapter1.Fill(CrmDataSet1.EmployeesData)
        ' This line of code is generated by Data Source Configuration Wizard
        ' EmployeesDataTableAdapter1.Fill(CrmDataSet1.EmployeesData)
    End Sub

    Private Sub Employee_Load(sender As Object, e As EventArgs) Handles MyBase.Load
        'TODO: This line of code loads data into the 'CRMDataSet.EmployeesData' table. You can move, or remove it, as needed.
        Me.EmployeesDataTableAdapter.Fill(Me.CRMDataSet.EmployeesData)
        'TODO: This line of code loads data into the 'CRMDataSet.EmployeesData' table. You can move, or remove it, as needed.
        Me.EmployeesDataTableAdapter.Fill(Me.CRMDataSet.EmployeesData)
        'TODO: This line of code loads data into the 'CRMDataSet.EmployeesData' table. You can move, or remove it, as needed.
        '  Me.EmployeesDataTableAdapter.Fill(Me.CRMDataSet.EmployeesData)

    End Sub

    Private Sub BirthdayDateEdit_EditValueChanged(sender As Object, e As EventArgs) Handles BirthdayDateEdit.EditValueChanged

    End Sub

    'Private Sub EmployeesDataBindingNavigatorSaveItem_Click(sender As Object, e As EventArgs) Handles MyBasesDataBindingNavigatorSaveItem.Click
    '    Me.Validate()
    '    Me.EmployeesDataBindingSource.EndEdit()
    '    Me.TableAdapterManager.UpdateAll(Me.CRMDataSet)

    'End Sub

    'Private Sub EmployeesDataBindingNavigatorSaveItem_Click_1(sender As Object, e As EventArgs) Handles MyBasesDataBindingNavigatorSaveItem.Click, MyBasesDataBindingNavigatorSaveItem.Click
    '    Me.Validate()
    '    Me.EmployeesDataBindingSource.EndEdit()
    '    Me.TableAdapterManager.UpdateAll(Me.CRMDataSet)

    'End Sub
End Class