Imports System.Data.SqlClient
Imports DevExpress.DataAccess.Sql

Public Class FinancialBawaqe
    Sub New()

        InitializeComponent()
        ' This line of code is generated by Data Source Configuration Wizard
        ' Fill a SqlDataSource
        '    SqlDataSource1.Fill()

        ' This line of code is generated by Data Source Configuration Wizard
        ' Fill a SqlDataSource
        SqlDataSource1.Fill()
    End Sub

    Private Sub Search()
        'Dim sql As New SQLControl
        'Dim cn As New SqlConnection(OrbakString)
        'Dim query As CustomSqlQuery = TryCast(SqlDataSource1.Queries(0), CustomSqlQuery)
        'Sql.WizCountRunQuery(" select *  from BOOKSRECPT")





        'Dim s As New DataSet()
        'Dim Table As New DataTable

        'SqlDataSource1.Fill()



    End Sub

    Private Sub FinancialBawaqe_Load(sender As Object, e As EventArgs) Handles MyBase.Load
        SqlDataSource1.Fill()
        '    GridControl1.DataSource = SqlDataSource1
    End Sub

    Private Sub SimpleButton1_Click(sender As Object, e As EventArgs)
        GridControl1.ShowPrintPreview()
    End Sub

    Private Sub SimpleButton2_Click(sender As Object, e As EventArgs)
        SqlDataSource1.Fill()
    End Sub

    Private Sub GridControl1_Click(sender As Object, e As EventArgs) Handles GridControl1.Click

    End Sub
End Class