Public Class FinancialChuqesQuery
    Sub New()

        InitializeComponent()
        ' This line of code is generated by Data Source Configuration Wizard

        ' This line of code is generated by Data Source Configuration Wizard
        ' Fill a SqlDataSource
        SqlDataSource1.Fill()
    End Sub

    Private Sub SimpleButton2_Click(sender As Object, e As EventArgs) Handles SimpleButton2.Click
        'Dim SqlString As String
        For i = 0 To GridView1.RowCount - 1
            Dim ChequeslID As Integer = CInt(GridView1.GetRowCellValue(i, "ID"))

        Next
    End Sub

    Private Sub FinancialChuqesQuery_Load(sender As Object, e As EventArgs) Handles MyBase.Load

    End Sub

    Sub GetCheksFromReader()
        '        Dim SqlString As String
        '        SqlString ="  Select ID, Checks.IB_BANK_ID,
        '       Checks.IB_BRANCH_ID,
        '       Checks."SORT_ID, Checks.CHECK_NO,
        '       Checks.ACCOUNT_NO, Checks.RUN_DATE,
        '       Checks.RUN_USER, Checks.FrontImage,
        '       Checks.Rearimage, BANKS.BANK_NAME
        '  from(dbo.Checks Checks
        '  Left
        '            Join dbo.BANKS BANKS
        '       On (BANKS.BANK_ID = Checks.IB_BANK_ID))
        'order by Checks.ID asc"

    End Sub
End Class