Public Class FinanceCheksReport
    Sub New()

        InitializeComponent()
        ' This line of code is generated by Data Source Configuration Wizard
        ChecksTableAdapter1.Fill(ClearingSystemDataSet1.Checks)
    End Sub

    Private Sub ChecksBindingNavigatorSaveItem_Click(sender As Object, e As EventArgs)
        Me.Validate()
        Me.ChecksBindingSource.EndEdit()
        Me.TableAdapterManager.UpdateAll(Me.ClearingSystemDataSet)

    End Sub

    Private Sub FinanceCheksReport_Load(sender As Object, e As EventArgs) Handles MyBase.Load
        'TODO: This line of code loads data into the 'ClearingSystemDataSet.Checks' table. You can move, or remove it, as needed.



    End Sub

    Private Sub IDTextBox1_TextChanged(sender As Object, e As EventArgs)




    End Sub

    Private Sub IDTextBox1_Leave(sender As Object, e As EventArgs)

    End Sub

    Private Sub IDTextBox_TextChanged(sender As Object, e As EventArgs)





    End Sub

    Private Sub IDNumericUpDown_ValueChanged(sender As Object, e As EventArgs)

    End Sub

    Private Sub IDTextEdit_EditValueChanged(sender As Object, e As EventArgs)

    End Sub

    Private Sub TextEdit1_EditValueChanged(sender As Object, e As EventArgs) Handles TextEdit1.EditValueChanged

        Try
            Dim IDValue As Long = CLng(TextEdit1.Text)
            Me.ChecksTableAdapter.FillByID(Me.ClearingSystemDataSet.Checks, IDValue)

        Catch ex As Exception
            MsgBox(ex.ToString)
        End Try

    End Sub

    Private Sub SimpleButton1_Click(sender As Object, e As EventArgs)

    End Sub

    Private Sub SimpleButton3_Click(sender As Object, e As EventArgs)

    End Sub


    Private Sub SimpleButton1_Click_1(sender As Object, e As EventArgs) Handles SimpleButton1.Click
        If Not Me.LayoutControl1.IsPrintingAvailable Then
            MessageBox.Show("The 'DevExpress.XtraPrinting' library is not found", "Error")
            Return
        End If

        ' Opens the Preview window.
        LayoutControl1.ShowPrintPreview()
    End Sub

    Private Sub GridControl1_Click_1(sender As Object, e As EventArgs) Handles GridControl1.Click

        Try
            Dim ChequeslID As Integer = CInt(TileView1.GetRowCellValue(TileView1.FocusedRowHandle, "ID"))
            Me.ChecksTableAdapter.FillByID(Me.ClearingSystemDataSet.Checks, ChequeslID)

        Catch ex As Exception
            MsgBox(ex.ToString)
        End Try
    End Sub
End Class