






Imports Excel = Microsoft.Office.Interop.Excel
Imports Microsoft.Office
Imports DevExpress.Spreadsheet

Public Class FinancialVouchers
    Sub New()

        InitializeComponent()
        ' This line of code is generated by Data Source Configuration Wizard
        ' Fill a ExcelDataSource
        ExcelDataSource1.Fill()
        ' This line of code is generated by Data Source Configuration Wizard
        ' Fill a ExcelDataSource
        ExcelDataSource2.Fill()
    End Sub

    Private Sub FinancialVouchers_Load(sender As Object, e As EventArgs) Handles MyBase.Load
        Me.BandedGridView1.BestFitColumns()
        Me.BandedGridView2.BestFitColumns()
    End Sub

    Private Sub SimpleButton1_Click(sender As Object, e As EventArgs) Handles SimpleButton1.Click

        '   Process.Start("EXCEL.EXE", """‪Z:\CRLite\Vouchers.xlsm""")


        System.Diagnostics.Process.Start("Z:\CRLite\Vouchers.xlsm")



    End Sub

    Private Sub SimpleButton2_Click(sender As Object, e As EventArgs) Handles SimpleButton2.Click
        ExcelDataSource1.Fill()
        ' This line of code is generated by Data Source Configuration Wizard
        ' Fill a ExcelDataSource
        ExcelDataSource2.Fill()
    End Sub

    Private Sub SimpleButton3_Click(sender As Object, e As EventArgs) Handles SimpleButton3.Click
        GridControl1.ShowPrintPreview()
    End Sub

    Private Sub SimpleButton4_Click(sender As Object, e As EventArgs) Handles SimpleButton4.Click
        GridControl2.ShowPrintPreview()
    End Sub

    Private Sub SimpleButton6_Click(sender As Object, e As EventArgs) Handles SimpleButton6.Click
        Me.BandedGridView1.BestFitColumns()
        Me.BandedGridView2.BestFitColumns()
    End Sub

    Private Sub SimpleButton5_Click(sender As Object, e As EventArgs) Handles SimpleButton5.Click
        System.Diagnostics.Process.Start("Z:\CRLite\Vouchers.xlsm")
    End Sub
End Class