Public Class FinanceChequsImages
    Sub New()

        InitializeComponent()
        ' This line of code is generated by Data Source Configuration Wizard

        ' This line of code is generated by Data Source Configuration Wizard
        'ChecksTableAdapter1.Fill(ClearingSystemDataSet1.Checks)
        ' This line of code is generated by Data Source Configuration Wizard
        ' Fill a SqlDataSource

    End Sub

    Private Sub FinanceChequsImages_Load(sender As Object, e As EventArgs) Handles MyBase.Load
        SqlDataSource1.Fill()
    End Sub
End Class