Imports DevExpress.XtraGrid.Views.Grid
Imports DevExpress.XtraGrid.Views.Grid.ViewInfo

Public Class FinanceSelectAccount
    Sub New()

        InitializeComponent()
        ' This line of code is generated by Data Source Configuration Wizard
        ' Fill a SqlDataSource
        SqlDataSource1.Fill()
        ' This line of code is generated by Data Source Configuration Wizard
        ' Fill a SqlDataSource
        '   SqlDataSource1.Fill()
        ' This line of code is generated by Data Source Configuration Wizard
        ' Fill a SqlDataSource
        '   SqlDataSource1.Fill()
        ' This line of code is generated by Data Source Configuration Wizard
        ' Fill a SqlDataSource
        '   SqlDataSource1.Fill()
        ' This line of code is generated by Data Source Configuration Wizard
        ' Fill a SqlDataSource
        '  SqlDataSource2.Fill()
    End Sub

    Private Sub FinanceSelectAccount_Load(sender As Object, e As EventArgs) Handles MyBase.Load
        'TODO: This line of code loads data into the 'WizCountDataSet.Accounts' table. You can move, or remove it, as needed.
        '    Me.AccountsTableAdapter.Fill(Me.WizCountDataSet.Accounts)
        '   SearchLookUpEdit3.datas = SqlDataSource1.Queries(1)
        SqlDataSource1.Fill()
    End Sub

    Private Sub SearchLookUpEdit3_EditValueChanged(sender As Object, e As EventArgs) Handles SearchLookUpEdit3.EditValueChanged, SearchLookUpEdit3.EditValueChanged
        Try
            Dim view As GridView = SearchLookUpEdit3.Properties.View
            Dim rowHandle As Integer = view.FocusedRowHandle
            Dim fieldName As String = "رقم التصنيف"
            Dim value As Object = view.GetRowCellValue(rowHandle, fieldName)
            SortText.Text = value.ToString
            If SearchLookUpEdit3.Text = "" Then SortText.Text = ""
        Catch ex As Exception
            Exit Sub
        End Try
    End Sub

    Private Sub TextEdit1_EditValueChanged(sender As Object, e As EventArgs) Handles AccNameText.EditValueChanged
        SearchAccounts()
    End Sub



    Private Sub SearchLookUpEdit1_EditValueChanged(sender As Object, e As EventArgs) Handles SearchLookUpEdit1.EditValueChanged
        Try
            Dim view As GridView = SearchLookUpEdit1.Properties.View
            Dim rowHandle As Integer = view.FocusedRowHandle
            Dim fieldName As String = "رقم الحساب"
            Dim value As Object = view.GetRowCellValue(rowHandle, fieldName)
            AccNoText.Text = value.ToString
            If SearchLookUpEdit1.Text = "" Then AccNoText.Text = ""
        Catch ex As Exception
            Exit Sub
        End Try


    End Sub

    Private Sub SearchLookUpEdit2_EditValueChanged(sender As Object, e As EventArgs) Handles SearchLookUpEdit2.EditValueChanged
        Try
            Dim view As GridView = SearchLookUpEdit2.Properties.View
            Dim rowHandle As Integer = view.FocusedRowHandle
            Dim fieldName As String = "رقم المنطقة"
            Dim value As Object = view.GetRowCellValue(rowHandle, fieldName)
            AreaText.Text = value.ToString
            If SearchLookUpEdit2.Text = "" Then AreaText.Text = ""
        Catch ex As Exception
            Exit Sub
        End Try
    End Sub

    Sub SearchAccounts()
        Dim sql As New SQLControl


        Dim SQLString As String = "  SELECT [AccountKey] ,[FullName],Country,SPhone,[AccSortNames].[sortcodename] ,[CostCodes].[CostCodeName]
                              FROM [ALHUDA].[dbo].[Accounts]
                              LEFT JOIN [ALHUDA].[dbo].AccSortNames ON [ALHUDA].[dbo].[Accounts].sortgroup = [ALHUDA].[dbo].AccSortNames.AccSortCode
                              LEFT JOIN [ALHUDA].[dbo].[CostCodes] ON [ALHUDA].[dbo].[Accounts].CostCode = [ALHUDA].[dbo].[CostCodes].[CostCode] where [AccountKey] is not null  "
        ' SQLString = SQLString + "  And [SortGroup] between 2000 and 2099  "
        If AccNoText.Text <> "" Then SQLString = SQLString + "  And [AccountKey] = '" & AccNoText.Text & "'"
        If SortText.Text <> "" Then SQLString = SQLString + "  And [SortGroup] = '" & SortText.Text & "'"
        If AreaText.Text <> "" Then SQLString = SQLString + "  And [Accounts].[CostCode] = '" & AreaText.Text & "'"
        If AccNameText.Text <> "" Then SQLString = SQLString + "  And [FullName] like '%" & AccNameText.Text & "%'"


        SQLString = SQLString + " order by [AccountKey] DESC "
        sql.WizCountRunQuery(SQLString)
        GridControl1.DataSource = sql.SQLDS.Tables(0)





    End Sub

    Private Sub SimpleButton1_Click(sender As Object, e As EventArgs) Handles SimpleButton1.Click
        GridControl1.ShowPrintPreview()
    End Sub



    Private Sub AccNoText_EditValueChanged(sender As Object, e As EventArgs) Handles AccNoText.EditValueChanged
        SearchAccounts()
    End Sub

    Private Sub SortText_EditValueChanged(sender As Object, e As EventArgs) Handles SortText.EditValueChanged
        SearchAccounts()
    End Sub

    Private Sub AreaText_EditValueChanged(sender As Object, e As EventArgs) Handles AreaText.EditValueChanged
        SearchAccounts()
    End Sub

    Private Sub gridView1_DoubleClick(ByVal sender As Object, ByVal e As EventArgs) Handles GridView1.DoubleClick
        Dim AccountID As Integer = CInt(GridView1.GetRowCellValue(GridView1.FocusedRowHandle, "AccountKey"))

        'If Me.Text = FinanceReceipt.Text Then
        '    My.Forms.FinanceReceipt.RecCustNoTextEdit.Text = AccountID.ToString
        '    '  Me.Hide()
        'End If
        'If Me.Text = OrpakCardsQuery.Text Then
        '    My.Forms.OrpakCardsQuery.FleetCode.Text = AccountID.ToString
        '    '   Me.Hide()
        'End If

        If Me.TextEdit1.Text = FinanceReceipt.Name.ToString Then
            Dim child As Form = Nothing
            For Each f As Form In Main.MdiChildren
                If TypeOf f Is FinanceReceipt Then
                    child = f
                    f.ActiveControl.Text = AccountID.ToString
                    MsgBox(f.ActiveControl.Text)
                    Exit For
                    End If
            Next f
            Me.Hide()
        End If

        If Me.TextEdit1.Text = OrpakCardsQuery.Name.ToString Then
            Dim child As Form = Nothing
            For Each f As Form In Main.MdiChildren
                If TypeOf f Is OrpakCardsQuery Then
                    child = f
                    f.ActiveControl.Text = AccountID.ToString
                    Exit For
                End If
            Next f
            Me.Hide()
        End If


        If Me.TextEdit1.Text = FinancialAccountingStatment.Name.ToString Then
            Dim child As Form = Nothing
            For Each f As Form In Main.MdiChildren
                If TypeOf f Is FinancialAccountingStatment Then
                    child = f
                    f.ActiveControl.Text = AccountID.ToString
                    Exit For
                End If
            Next f
            Me.Hide()
        End If

    End Sub

    Private Sub GridControl1_Click(sender As Object, e As EventArgs) Handles GridControl1.Click

    End Sub

    Private Sub PanelControl1_Paint(sender As Object, e As PaintEventArgs) Handles PanelControl1.Paint

    End Sub

    Private Sub FinanceSelectAccount_Leave(sender As Object, e As EventArgs) Handles Me.Leave
        '   My.Forms.FinanceReceipt.RecCustNoTextEdit.Text = CInt(GridView1.GetRowCellValue(GridView1.FocusedRowHandle, "AccountKey")).ToString
    End Sub
End Class

