Imports System.ComponentModel
Imports DevExpress.XtraGrid.Views.Base
Imports DevExpress.XtraGrid.Views.Grid

Public Class FinancialChequesBack
    Sub New()

        InitializeComponent()
        Me.KeyPreview = True
        ' This line of code is generated by Data Source Configuration Wizard
        '  FinancialChequesBackTableAdapter1.Fill(CrmDataSet1.FinancialChequesBack)
        ' This line of code is generated by Data Source Configuration Wizard
        ' Fill a SqlDataSource
        '  SqlDataSource1.Fill()
    End Sub
    Private Sub FinancialChequesBack_KeyDown(sender As Object, e As KeyEventArgs) Handles Me.KeyDown
        If e.KeyCode = Keys.F2 Then
            Saving()
        End If

        Try
            If e.KeyCode = Keys.Insert Then
                AddingNew()
            End If
        Catch ex As Exception

        End Try
    End Sub
    Private Sub FinancialChequesBack_Load(sender As Object, e As EventArgs) Handles MyBase.Load
        'TODO: This line of code loads data into the 'WizCountDataSet.Cheqs1' table. You can move, or remove it, as needed.
        Me.Cheqs1TableAdapter.Fill(Me.WizCountDataSet.Cheqs1)
        'TODO: This line of code loads data into the 'CRMDataSet.FinancialChequesBack' table. You can move, or remove it, as needed.
        Me.FinancialChequesBackTableAdapter.Fill(Me.CRMDataSet.FinancialChequesBack)
        'TODO: This line of code loads data into the 'CRMDataSet.FinancialChequesBack' table. You can move, or remove it, as needed.
        Me.FinancialChequesBackTableAdapter.Fill(Me.CRMDataSet.FinancialChequesBack)
        Me.Cheqs1TableAdapter.Fill(Me.WizCountDataSet.Cheqs1)
        Me.FinancialChequesBackTableAdapter.FillByID(Me.CRMDataSet.FinancialChequesBack, -1)
    End Sub
    Private Sub GridView1_ValidateRow(sender As Object, e As ValidateRowEventArgs)




    End Sub
    Private Sub BandedGridView1_ShowingEditor(sender As Object, e As CancelEventArgs) Handles BandedGridView1.ShowingEditor

        'If Me.BandedGridView1.GetRowCellValue(BandedGridView1.FocusedRowHandle, "Currency") Is DBNull.Value Then
        '    BandedGridView1.SetRowCellValue(BandedGridView1.FocusedRowHandle, BandedGridView1.Columns("Currency"), "شيكل")
        'End If

        If BandedGridView1.GetRowCellValue(BandedGridView1.FocusedRowHandle, "InputDate") Is DBNull.Value Then
            BandedGridView1.SetRowCellValue(BandedGridView1.FocusedRowHandle, BandedGridView1.Columns("InputDate"), Today)
        End If

        If BandedGridView1.GetRowCellValue(BandedGridView1.FocusedRowHandle, "ChequeStatus") Is DBNull.Value Then
            BandedGridView1.SetRowCellValue(BandedGridView1.FocusedRowHandle, BandedGridView1.Columns("ChequeStatus"), "راجع")
        End If

        If BandedGridView1.GetRowCellValue(BandedGridView1.FocusedRowHandle, "BankName") Is DBNull.Value Then
            BandedGridView1.SetRowCellValue(BandedGridView1.FocusedRowHandle, BandedGridView1.Columns("BankName"), ComboBoxEdit1.SelectedItem)
        End If

        If BandedGridView1.GetRowCellValue(BandedGridView1.FocusedRowHandle, "BankAccNo") Is DBNull.Value Then
            BandedGridView1.SetRowCellValue(BandedGridView1.FocusedRowHandle, BandedGridView1.Columns("BankAccNo"), ComboBoxEdit1.SelectedItem)
        End If

    End Sub


    Private Sub Saving()
        Try
            If ComboBoxEdit1.Text = "" Then MsgBox("يجب اختيار البنك ") : Exit Sub
            Me.Validate()
            Me.FinancialChequesBackBindingSource.EndEdit()
            '  Me.FinancialChequesBackBindingSource
            Me.TableAdapterManager1.UpdateAll(Me.CRMDataSet)
            Me.FinancialChequesBackTableAdapter.FillByID(Me.CRMDataSet.FinancialChequesBack, -1)
            DevExpress.XtraEditors.XtraMessageBox.Show("تم حفظ السند ")
        Catch ex As Exception
            MsgBox("لا يكن حفظ السند")
            MsgBox(ex.ToString)
        End Try


    End Sub

    Private Sub SimpleButton1_Click(sender As Object, e As EventArgs) Handles SimpleButton1.Click
        Saving()

    End Sub

    Private Sub SimpleButton2_Click(sender As Object, e As EventArgs) Handles SimpleButton2.Click
        AddingNew()
    End Sub
    Private Sub AddingNew()

        Try
            FinancialChequesBackBindingSource.AddNew()
            BandedGridView1.BestFitColumns()
        Catch ex As Exception
            MsgBox("لا يكن اضافة جديد")
        End Try


    End Sub



    Private Sub repositoryItemSearchLookUpEdit1_EditValueChanged(sender As Object, e As EventArgs) Handles RepositoryItemSearchLookUpEdit1.EditValueChanged
        Dim edit As DevExpress.XtraEditors.SearchLookUpEdit = TryCast(sender, DevExpress.XtraEditors.SearchLookUpEdit)
        Dim rowHandle As Integer = edit.Properties.GetIndexByKeyValue(edit.EditValue)
        Dim row As Object = edit.Properties.View.GetRow(rowHandle)

        Dim valu As String = TryCast(row, DataRowView).Row("ValueDate").ToString()
        BandedGridView1.SetRowCellValue(BandedGridView1.FocusedRowHandle, BandedGridView1.Columns("ChequeDate"), valu)

        Dim valu2 As String = TryCast(row, DataRowView).Row("SuFDlr").ToString()
        BandedGridView1.SetRowCellValue(BandedGridView1.FocusedRowHandle, BandedGridView1.Columns("AmountNIS"), valu2)

        Dim valu3 As String = TryCast(row, DataRowView).Row("SuF").ToString()
        BandedGridView1.SetRowCellValue(BandedGridView1.FocusedRowHandle, BandedGridView1.Columns("Amount"), valu3)

        Dim valu4 As String = TryCast(row, DataRowView).Row("AccName").ToString()
        BandedGridView1.SetRowCellValue(BandedGridView1.FocusedRowHandle, BandedGridView1.Columns("AccountName"), valu4)

        Dim valu5 As String = TryCast(row, DataRowView).Row("AccKey").ToString()
        BandedGridView1.SetRowCellValue(BandedGridView1.FocusedRowHandle, BandedGridView1.Columns("AccID"), valu5)

        Dim valu6 As String = TryCast(row, DataRowView).Row("Currency").ToString()
        BandedGridView1.SetRowCellValue(BandedGridView1.FocusedRowHandle, BandedGridView1.Columns("Currency"), valu6)


        Dim valu8 As String = TryCast(row, DataRowView).Row("BankAccNum").ToString()
        BandedGridView1.SetRowCellValue(BandedGridView1.FocusedRowHandle, BandedGridView1.Columns("BankAccNo"), valu8)

        Dim valu9 As String = TryCast(row, DataRowView).Row("CheqNumber").ToString()
        BandedGridView1.SetRowCellValue(BandedGridView1.FocusedRowHandle, BandedGridView1.Columns("ChequNO"), valu9)

        Dim valu10 As String = TryCast(row, DataRowView).Row("DepositID").ToString()
        BandedGridView1.SetRowCellValue(BandedGridView1.FocusedRowHandle, BandedGridView1.Columns("DepositID"), valu10)



        If TryCast(row, DataRowView).Row("Currency").ToString() = "NIS" Then
            Dim valu7 As String = TryCast(row, DataRowView).Row("SuF").ToString()
            BandedGridView1.SetRowCellValue(BandedGridView1.FocusedRowHandle, BandedGridView1.Columns("AmountNIS"), valu7)
        End If

        Try
            Dim DID As Integer = 0
            Dim DName As String = " "
            Dim sql As New SQLControl
            Dim SqlString As String = "  SELECT DebName , TransDebID      FROM [ALHUDA].[dbo].[JurnalTrans]
                                     WHERE [ALHUDA].[dbo].[JurnalTrans]. BatchNo =9999  and StockID =" & valu10
            sql.WizCountRunQuery(SqlString)
            DID = CInt(sql.SQLDS.Tables(0).Rows(0).Item("TransDebID").ToString)
            DName = CStr(sql.SQLDS.Tables(0).Rows(0).Item("DebName").ToString)
            BandedGridView1.SetRowCellValue(BandedGridView1.FocusedRowHandle, BandedGridView1.Columns("TransDebID"), DID)
            BandedGridView1.SetRowCellValue(BandedGridView1.FocusedRowHandle, BandedGridView1.Columns("DebName"), DName)
        Catch ex As Exception

        End Try

        Try
            Dim Sql As New SQLControl
            Dim SqlString As String
            SqlString = " Select ID from [CRM].[dbo].[FinancialChequesBack] 
                          Where ChequNO='" & valu9 & "' and Amount='" & valu3 & "' and
                          ChequeDate='" & Format(CDate(valu), "yyyy-MM-dd") & "' and BankAccNo='" & valu8 & "' and ChequeStatus='مقيد' "
            Sql.CRMRunQuery(SqlString)
            If Sql.SQLDS.Tables(0).Rows.Count > 0 Then
                MsgBox("الشيك مقيد")
                BandedGridView1.SetRowCellValue(BandedGridView1.FocusedRowHandle, BandedGridView1.Columns("ChequeStatus"), "مقيد")
            End If
        Catch ex As Exception
            MsgBox(ex.ToString)
        End Try


    End Sub

    Private Sub SimpleButton3_Click(sender As Object, e As EventArgs) Handles SimpleButton3.Click
        Me.FinancialChequesBackBindingSource.RemoveCurrent()
    End Sub

    Private Sub NavigationPane1_Click(sender As Object, e As EventArgs) Handles NavigationPane1.Click
        If Me.NavigationPane1.SelectedPageIndex = 2 Then
            Me.FinancialChequesBackTableAdapter.Fill(Me.CRMDataSet.FinancialChequesBack)
            GridView1.ActiveFilterString = "[ChequeStatus] ='راجع' "
        End If
        If Me.NavigationPane1.SelectedPageIndex = 1 Then
            Me.FinancialChequesBackTableAdapter.FillByID(Me.CRMDataSet.FinancialChequesBack, -1)
        End If

    End Sub

    Private Sub SimpleButton4_Click(sender As Object, e As EventArgs) Handles SimpleButton4.Click
        '     Me.FinancialChequesBackTableAdapter.Fill(Me.CRMDataSet.FinancialChequesBack)
        If ComboChekStatus.Text <> "الكل" Then Me.FinancialChequesBackTableAdapter.FillByStatus(Me.CRMDataSet.FinancialChequesBack, "راجع")
        '   If ComboChekStatus.Text = "الكل" Then Me.FinancialChequesBackTableAdapter.Fill(Me.CRMDataSet.FinancialChequesBack)

        '   Me.FinancialChequesBackTableAdapter.Fill(Me.CRMDataSet.FinancialChequesBack, "محصل")
    End Sub

    Private Sub ComboChekStatus_SelectedIndexChanged(sender As Object, e As EventArgs) Handles ComboChekStatus.SelectedIndexChanged
        If ComboChekStatus.Text <> "الكل" Then Me.FinancialChequesBackTableAdapter.FillByStatus(Me.CRMDataSet.FinancialChequesBack, ComboChekStatus.Text)
        If ComboChekStatus.Text = "الكل" Then Me.FinancialChequesBackTableAdapter.Fill(Me.CRMDataSet.FinancialChequesBack)

    End Sub

    Private Sub SimpleButton7_Click(sender As Object, e As EventArgs) Handles SimpleButton7.Click
        '  Me.Cheqs1TableAdapter.Fill(Me.WizCountDataSet.Cheqs1)
        GridView1.BestFitColumns()
        Me.FinancialChequesBackTableAdapter.Fill(Me.CRMDataSet.FinancialChequesBack)
    End Sub

    Private Sub SimpleButton6_Click(sender As Object, e As EventArgs) Handles SimpleButton6.Click
        Me.Validate()
        Me.FinancialChequesBackBindingSource.EndEdit()
        Me.TableAdapterManager1.UpdateAll(Me.CRMDataSet)
    End Sub

    Private Sub RepositoryPrint_ButtonClick(sender As Object, e As DevExpress.XtraEditors.Controls.ButtonPressedEventArgs) Handles RepositoryPrint.ButtonClick
        ChequeImage()
    End Sub

    Private Sub RepositoryChequeImage_ButtonClick(sender As Object, e As DevExpress.XtraEditors.Controls.ButtonPressedEventArgs) Handles RepositoryChequeImage.ButtonClick
        ChequeImage()

    End Sub

    Private Sub ChequeImage()
        Try
            Dim ChequesNo As String
            Dim BankAccNum As String
            ChequesNo = CStr(BandedGridView1.GetRowCellValue(BandedGridView1.FocusedRowHandle, "ChequNO"))
            BankAccNum = CStr(BandedGridView1.GetRowCellValue(BandedGridView1.FocusedRowHandle, "BankAccNo"))
            With FinanceChequsImages
                .SqlDataSource1.Queries(0).Parameters(0).Value = ChequesNo
                .SqlDataSource1.Queries(0).Parameters(1).Value = BankAccNum
                .SqlDataSource1.Fill()
            End With
            FinanceChequsImages.Show()
        Catch ex As Exception
            MsgBox("لا يوجد صورة متوفرة")
            MsgBox(ex.ToString)

        End Try
    End Sub

    Private Sub SimpleButton5_Click(sender As Object, e As EventArgs) Handles SimpleButton5.Click
        FinancialChequesBackGridControl1.ShowPrintPreview()
    End Sub

End Class