Public Class FinancialAccountsAll
    Sub New()

        InitializeComponent()
        ' This line of code is generated by Data Source Configuration Wizard
        '    AccountsTableAdapter1.Fill(AccountsDataSet1.Accounts)
        ' This line of code is generated by Data Source Configuration Wizard

        ' This line of code is generated by Data Source Configuration Wizard
        ' Fill a SqlDataSource
        SqlDataSource1.Fill()
    End Sub
End Class