Imports System.Windows.Controls
Imports DevExpress.XtraBars.Navigation
Imports DevExpress.XtraGrid.Views.Base
Imports DevExpress.XtraGrid.Views.Grid
Imports DevExpress.XtraReports.UI

Public Class FinanceReceipt

    Sub New()

        InitializeComponent()
        ' This line of code is generated by Data Source Configuration Wizard
        Me.KeyPreview = True
        ' This line of code is generated by Data Source Configuration Wizard
        ' Fill a SqlDataSource

    End Sub

    Dim sql As New SQLControl
    Dim i As Integer


    Private Sub FinanceReceipt_Load(sender As Object, e As EventArgs) Handles MyBase.Load
        'TODO: This line of code loads data into the 'WizCountDataSet.Accounts1' table. You can move, or remove it, as needed.
        Me.Accounts1TableAdapter.Fill(Me.WizCountDataSet.Accounts1)
        Me.ReceiptDataTableAdapter.Fill(Me.CRMDataSet.ReceiptData)
        Me.ReceiptDataBindingSource.MoveLast()
        Me.KeyPreview = True

        DateEditTo.DateTime = CDate(DateTime.Now.ToString("yyyy-MM-dd 00:00:00.000"))
        DateEditFrom.DateTime = CDate(DateTime.Now.AddYears(-1).ToString("yyyy-MM-dd 00:00:00.000"))

        DateEdit2.DateTime = CDate(DateTime.Now.ToString("yyyy-MM-dd 00:00:00.000"))
        DateEdit1.DateTime = CDate(DateTime.Now.AddYears(-1).ToString("yyyy-MM-dd 00:00:00.000"))



    End Sub

    Private Sub SimpleButton1_Click(sender As Object, e As EventArgs) Handles SimpleButton1.Click

        SaviingReceipt()

    End Sub

    Sub SaviingReceipt()

        RecCustNoTextEdit.Select()


        If RecCustNoTextEdit.Text = "" Or RecCustNameTextEdit.Text = "" Or RecDateDateEdit.Text = "" Or RecCurrTextEdit.Text = "" Or RecSmallCurrName.Text = "" _
            Or AmountInNisText.Text = "" Or RecTotalSpinEdit.Text = "" Then
            MsgBox("الرجاء تعبئة كل البيانات المطلوبة")
            Exit Sub
        End If


        If RecNoteTextEdit.Text = "" Then MsgBox("لا تنسى كتابة ملاحظة") : Exit Sub


        'Dim TasksCountAnnswer As MsgBoxResult
        'If CheckCRMTaskCount() = True Then TasksCountAnnswer = MsgBox("لم يتم اغلاق اي مهمة هل تريد المتابعة", vbYesNo)
        'If TasksCountAnnswer = vbNo Then Exit Sub

        'Deleteemptyrows()

        'If SumChequesLabel.Text <> RecChequeSpinEdit.Text Then
        '    MsgBox("خطا: مجموع الشيكات لا يتفق مع المبلغ في خانة الشيكات")
        '    Exit Sub
        'End If

        CheckTasks()

        If CInt(RecNOSpinEdit.Text) < 0 Then
            For i As Integer = 0 To Me.GridView5.RowCount - 1
                Me.GridView5.SetRowCellValue(i, "ChequeReceiptNo", Me.ReceiptDataTableAdapter.GetMaxRec.ToString)
            Next i
            RecStatusSpinEdit.EditValue = 1
        End If

        AddEvents("تنبيه", "  تم قبض من الزبون " & " " & RecCustNameTextEdit.Text, Me.Text, "1800013", My.Settings.UserName, "True")
        AddEvents("تنبيه", "  تم قبض من الزبون " & " " & RecCustNameTextEdit.Text, Me.Text, "1800102", My.Settings.UserName, "True")
        AddEvents("تنبيه", "  تم قبض من الزبون " & " " & RecCustNameTextEdit.Text, Me.Text, "1800666", My.Settings.UserName, "True")


        SaveEdit()




    End Sub

    Private Sub SaveEdit()

        Me.Validate()
        Me.ChequeDataBindingSource.EndEdit()
        Me.ReceiptDataBindingSource.EndEdit()

        Dim deletedOrders As CRMDataSet.ChequeDataDataTable = CType(
        CRMDataSet.ChequeData.GetChanges(Data.DataRowState.Deleted), CRMDataSet.ChequeDataDataTable)

        Dim newOrders As CRMDataSet.ChequeDataDataTable = CType(
        CRMDataSet.ChequeData.GetChanges(Data.DataRowState.Added), CRMDataSet.ChequeDataDataTable)

        Dim modifiedOrders As CRMDataSet.ChequeDataDataTable = CType(
        CRMDataSet.ChequeData.GetChanges(Data.DataRowState.Modified), CRMDataSet.ChequeDataDataTable)

        Try
            ' Remove all deleted orders from the Orders table.
            If Not deletedOrders Is Nothing Then
                ChequeDataTableAdapter.Update(deletedOrders)
            End If

            ' Update the Customers table.
            ReceiptDataTableAdapter.Update(CRMDataSet.ReceiptData)

            ' Add new orders to the Orders table.
            If Not newOrders Is Nothing Then
                ChequeDataTableAdapter.Update(newOrders)
            End If

            ' Update all modified Orders.
            If Not modifiedOrders Is Nothing Then
                ChequeDataTableAdapter.Update(modifiedOrders)
            End If

            CRMDataSet.AcceptChanges()

            DevExpress.XtraEditors.XtraMessageBox.Show("تم حفظ سند القبض")

            '  EndCRMTask()

            PrintRec()

            Me.ChequeDataBindingSource.AddNew()
            Me.ReceiptDataBindingSource.AddNew()
            ClearRecData()
        Catch ex As Exception
            MsgBox("خطا: الرجاء اعادة فحص البيانات")
            MsgBox(ex.ToString)
        Finally
            If Not deletedOrders Is Nothing Then
                deletedOrders.Dispose()
            End If

            If Not newOrders Is Nothing Then
                newOrders.Dispose()
            End If

            If Not modifiedOrders Is Nothing Then
                modifiedOrders.Dispose()
            End If
            ''''''''

        End Try
    End Sub

    'Sub Deleteemptyrows()


    '    Dim blank As Boolean = True
    '    For Each _row As DataGridViewRow In ChequeDataDataGridView.Rows
    '        blank = True
    '        For i As Integer = 0 To _row.Cells.Count - 1
    '            If _row.Cells(i).Value IsNot Nothing AndAlso _row.Cells(i).Value IsNot "" Then
    '                blank = False
    '                Exit For
    '            End If
    '        Next
    '        If blank Then
    '            If Not _row.IsNewRow Then
    '                ChequeDataDataGridView.Rows.Remove(_row)
    '            End If
    '        End If
    '    Next

    'End Sub

    Private Sub SimpleButton4_Click(sender As Object, e As EventArgs) Handles SimpleButton4.Click
        Me.ReceiptDataBindingSource.CancelEdit()
        ReceiptDataBindingSource.MoveFirst()
    End Sub

    Private Sub SimpleButton2_Click(sender As Object, e As EventArgs) Handles SimpleButton2.Click


        NewReceipt()
    End Sub

    Private Sub NewReceipt()
        If CInt(RecNOSpinEdit.Text) < 0 Then
            ClearRecData()
            Exit Sub
        End If

        Try
            Me.ChequeDataBindingSource.AddNew()
            Me.ReceiptDataBindingSource.AddNew()
            ClearRecData()
        Catch ex As Exception
            MsgBox(ex.ToString)
        End Try

        RecCustNoTextEdit.Select()
    End Sub

    Private Sub ClearRecData()
        Try
            RecCustNoTextEdit.Text = ""
            RecCustNameTextEdit.Text = ""
            RecCurrTextEdit.Text = "شيكل"
            RecSmallCurrName.Text = "اغورة"
            RecCurrRate.Text = "1"
            AmountInNisText.EditValue = 0
            RecCashSpinEdit.Text = "0"
            RecChequeSpinEdit.Text = "0"
            RecOtherSpinEdit.Text = "0"
            RecTotalSpinEdit.Text = "0"
            RecNoteTextEdit.Text = ""
            RecDateDateEdit.EditValue = Today
            Me.RecDeviceNameTextEdit.Text = My.Settings.DeviceName
            Me.RecUserTextEdit.Text = My.Settings.UserName
            RecAuditSpinEdit.EditValue = 0
            RecInputDateDateEdit.EditValue = Today
            RecStatusSpinEdit.EditValue = 0
            RecCustNoTextEdit.Select()
            ''SumChequesLabel.Text = "0"
            RecOwnerTextEdit.Text = My.Settings.UserName
            GridControl4.DataSource = ""
            TextEditAccChequeNO.Text = "0"
            TextEditChequeNO.Text = "0"
            TextEditChequesTotal.Text = "0"
            TextEditAccChequesTotal.Text = "0"
        Catch ex As Exception
            MsgBox("خطا لا يمكن حذف البيانات")
        End Try

    End Sub

    Private Sub SimpleButton3_Click(sender As Object, e As EventArgs) Handles SimpleButton3.Click
        Me.ReceiptDataBindingSource.CancelEdit()
        Me.ReceiptDataBindingSource.MoveNext()
    End Sub

    Private Sub SimpleButton5_Click(sender As Object, e As EventArgs) Handles SimpleButton5.Click
        Me.ReceiptDataBindingSource.CancelEdit()
        Try
            Me.ReceiptDataBindingSource.EndEdit()
            Me.ReceiptDataBindingSource.MovePrevious()
        Catch ex As System.Exception
            System.Windows.Forms.MessageBox.Show(ex.Message)
        End Try
    End Sub

    Private Sub SimpleButton6_Click(sender As Object, e As EventArgs) Handles SimpleButton6.Click
        Me.ReceiptDataBindingSource.CancelEdit()
        Me.ReceiptDataBindingSource.MoveLast()
    End Sub

    Private Sub RecNOSpinEdit_EditValueChanged(sender As Object, e As EventArgs) Handles RecNOSpinEdit.EditValueChanged

        If RecNOSpinEdit.Text = "" Then Exit Sub
        Try
            Me.ChequeDataTableAdapter.FillBy(Me.CRMDataSet.ChequeData, (CType(RecNOSpinEdit.Text, Integer)))
            'Me.ReceiptDataTableAdapter.FillBy(Me.CRMDataSet.ReceiptData, (CType(RecNOSpinEdit.Text, Integer)))
            'Me.ChequeDataTableAdapter.FillBy(Me.CRMDataSet.ChequeData, (CType(RecNOSpinEdit.Text, Integer)))
        Catch ex As System.Exception
            System.Windows.Forms.MessageBox.Show(ex.Message)
        End Try

        If CInt(RecNOSpinEdit.Text) > 0 Then
            '  PanelControl3.Enabled = False
            '  PanelControl4.Enabled = False
            'PanelControl9.Enabled = False
            '    PanelControl5.Enabled = False
            '    GroupControl1.Enabled = False
            'PanelControl2.Enabled = False
            SimpleButton1.Enabled = False
        Else
            '  PanelControl3.Enabled = True
            '   PanelControl4.Enabled = True
            ' PanelControl9.Enabled = True
            '  PanelControl5.Enabled = True
            '   GroupControl1.Enabled = True
            '  PanelControl2.Enabled = True
            SimpleButton1.Enabled = True
        End If

    End Sub

    Private Sub Financereceipt_KeyDown(sender As Object, e As KeyEventArgs) Handles Me.KeyDown
        If e.KeyCode = Keys.F3 Then
            SaviingReceipt()
        ElseIf e.KeyCode = Keys.F6 Then
            NewReceipt()
            'ElseIf e.KeyCode = Keys.Enter Then
            '    SendKeys.Send("{TAB}")
        End If
    End Sub




    'Private Sub SumCheks()

    '    Try
    '        Dim SumCheqs As Double = 0
    '        Dim CountCheqs As Double = -1
    '        If ChequeDataDataGridView.Rows(i).Cells(5).Value.ToString <> "" Then
    '            For i As Integer = 0 To Me.ChequeDataDataGridView.Rows.Count - 1
    '                SumCheqs += Convert.ToDouble(ChequeDataDataGridView.Rows(i).Cells(5).Value)
    '                CountCheqs += 1
    '            Next i
    '            RecChequeSpinEdit.EditValue = SumCheqs
    '            TextEditChequesTotal.EditValue = SumCheqs
    '            TextEditChequeNO.EditValue = CountCheqs

    '            TextEditAccChequesTotal.EditValue = GetSumCheks(CStr(DateTime.Now.ToString("yyyy-MM-dd 00:00:00.000")), RecCustNoTextEdit.Text) + Val(TextEditChequesTotal.EditValue)
    '            TextEditAccChequeNO.EditValue = GetCountCheks(CStr(DateTime.Now.ToString("yyyy-MM-dd 00:00:00.000")), RecCustNoTextEdit.Text) + Val(TextEditChequeNO.EditValue)
    '            TextEditAccountBalance.EditValue = GetAccBalance(CStr(Format(Today, "yyyy-MM-dd")), RecCustNoTextEdit.Text) - Val(AmountInNisText.EditValue)


    '        End If
    '    Catch ex As Exception

    '    End Try
    'End Sub



    Private Sub SimpleButton7_Click_1(sender As Object, e As EventArgs) Handles SimpleButton7.Click
        Dim report As New FinancialReceiptReport()
        report.Parameter1.Value = Me.RecNOSpinEdit.EditValue
        report.Parameter2.Value = TextEdit1.Text
        report.Parameter1.Visible = False
        report.Parameter2.Visible = False
        Dim printTool As New ReportPrintTool(report)
        printTool.ShowPreviewDialog()


    End Sub

    Private Sub RecTotalSpinEdit_EditValueChanged(sender As Object, e As EventArgs) Handles RecNOSpinEdit.EditValueChanged
        Try
            Dim aa As Decimal
            aa = CDec(RecTotalSpinEdit.Text)
            Me.TextEdit1.Text = NoToTxt(aa, RecCurrTextEdit.Text, "اغورة")
        Catch
            Exit Sub
        End Try

    End Sub

    Private Sub RecCurrTextEdit_SelectedIndexChanged(sender As Object, e As EventArgs) Handles RecCurrTextEdit.SelectedIndexChanged
        If RecCurrTextEdit.Text = "شيكل" Then Me.RecSmallCurrName.Text = "اغورة"
        If RecCurrTextEdit.Text = "دولار" Then Me.RecSmallCurrName.Text = "سنت"
        If RecCurrTextEdit.Text = "يورو" Then Me.RecSmallCurrName.Text = "سنت"
        If RecCurrTextEdit.Text = "دينار" Then Me.RecSmallCurrName.Text = "قرش"

        Write()

        CalcTotal()

    End Sub

    Private Sub Write()
        Try
            Dim aa As Decimal
            aa = CDec(RecTotalSpinEdit.Text)
            Me.TextEdit1.Text = NoToTxt(aa, RecCurrTextEdit.Text, RecSmallCurrName.Text)
        Catch
            Exit Sub
        End Try
    End Sub

    Private Sub RecRateSpinEdit_EditValueChanged(sender As Object, e As EventArgs)
        CalcTotal()
        CalcInNis()

    End Sub

    Private Sub RecTotalSpinEdit_EditValueChanged_1(sender As Object, e As EventArgs)
        CalcInNis()

    End Sub

    Private Sub CalcTotal()
        Try
            RecTotalSpinEdit.Text = CType(CDec(RecCashSpinEdit.Text) + CDec(RecChequeSpinEdit.Text) + CDec(RecOtherSpinEdit.Text), String)
            AmountInNisText.Text = CType(CType(CDec(RecTotalSpinEdit.Text) * CDec(RecCurrRate.Text), Decimal), String)
            TextEditAccountBalance.EditValue = Val(TextEditAccountBalance.EditValue) - Val(AmountInNisText.EditValue)
        Catch
            Exit Sub
        End Try
    End Sub

    Private Sub RecCashSpinEdit_EditValueChanged(sender As Object, e As EventArgs)
        CalcTotal()
    End Sub

    Private Sub RecChequeSpinEdit_EditValueChanged(sender As Object, e As EventArgs)
        CalcTotal()
    End Sub

    Private Sub RecOtherSpinEdit_EditValueChanged(sender As Object, e As EventArgs)
        CalcTotal()
    End Sub

    Private Sub CalcInNis()
        Try
            AmountInNisText.Text = CType(CDec(RecTotalSpinEdit.Text) * CDec(RecSmallCurrName.Text), String)
            Write()
        Catch
            Exit Sub
        End Try
    End Sub

    Private Sub SimpleButton8_Click(sender As Object, e As EventArgs) Handles SimpleButton8.Click

        PrintRec()

        'If SumChequesLabel.Text <> RecChequeSpinEdit.Text Then
        '    MsgBox("خطا: مجموع الشيكات لا يتفق مع المبلغ في خانة الشيكات")
        '    Exit Sub
        'End If





    End Sub

    Private Sub ChequeDataDataGridView_CellLeave(sender As Object, e As DataGridViewCellEventArgs)

    End Sub

    Private Sub SimpleButton9_Click(sender As Object, e As EventArgs) Handles SimpleButton9.Click
        ' PanelControl3.Enabled = True
        '   PanelControl4.Enabled = True
        'PanelControl9.Enabled = True
        '    PanelControl5.Enabled = True
        '   GroupControl1.Enabled = True
        'PanelControl2.Enabled = True
        SimpleButton1.Enabled = True
    End Sub

    Private Sub PrintRec()

        Try
            Dim report As New FinancialReceiptReport()
            report.Parameter1.Value = Me.RecNOSpinEdit.EditValue
            report.Parameter2.Value = TextEdit1.Text
            report.Parameter1.Visible = False
            report.Parameter2.Visible = False
            report.Balance.Visible = False
            If CheckEdit1.Checked = True Then
                report.Balance.Value = GetAccBalance(CStr(Format(Today, "yyyy-MM-dd")), RecCustNoTextEdit.Text)
                report.ChecksTotal.Value = GetSumCheks(CStr(DateTime.Now.ToString("yyyy-MM-dd 00:00:00.000")), RecCustNoTextEdit.Text) + CInt(RecChequeSpinEdit.EditValue)
                report.ChecksCount.Value = GetCountCheks(CStr(DateTime.Now.ToString("yyyy-MM-dd 00:00:00.000")), RecCustNoTextEdit.Text) + CInt(Me.GridView5.RowCount - 1)

            Else
                report.Balance.Value = ""
            End If
            report.CreateDocument()
            report.PrintingSystem.ShowMarginsWarning = False
            report.Print()
        Catch ex As Exception
            MsgBox("خطا: لم يتمكن البرنامج من طباعة سند القبض")
            MsgBox(ex.ToString)
        End Try

    End Sub

    Private Sub NavigationPane1_Click(sender As Object, e As EventArgs) Handles NavigationPane1.Click

    End Sub

    Private Sub AccounStatment(FromDate As String, ToDate As String)

        Try

            Dim AccountStatmentss = " SELECT       JVALUEDATE  AS ALIAS6F,    JREFERANCE  AS ALIAS8F,  JREF2  AS ALIAS9F,  JDESCRIPTION  AS ALIAS10F,   CASE JMDEBITCREDIT WHEN 1 THEN  JMSUF  ELSE 0 END AS ALIAS12F_DEB, CASE JMDEBITCREDIT WHEN 0 THEN  JMSUF  ELSE 0 END AS ALIAS12F_CR " _
                        & " from RPHSTRANSRETRIV" _
                        & " WHERE          ( JMACCOUNTKEY = '" & RecCustNoTextEdit.Text & "'  AND ('" & ToDate & "' >= JVALUEDATE) AND ('" & FromDate & "' <= JVALUEDATE) AND ('12/31/2050' >= JDUEDATE) AND ('01/01/1980' <= JDUEDATE) AND ('12/31/2050' >= JDATF3) AND ('01/01/1980' <= JDATF3) AND (0 <> JMSUF) )  AND JTYPE<>1 AND JTYPE <>2 AND ((JSTATUS = 1 AND JTYPE<>1) OR (JSTATUS = 0 AND JTYPE=1)) AND ADUMI <> 3 " _
                        & " ORDER BY                JMACCOUNTKEY ASC  , JVALUEDATE ASC  , JMID ASC "

            Dim DebitBalance = " SELECT   cast(  sum( JMSUF ) as decimal(10,2)) as Debit    " _
            & " from RPHSTRANSRETRIV" _
            & " WHERE   JMDEBITCREDIT=1 and       ( JMACCOUNTKEY = '" & RecCustNoTextEdit.Text & "'  AND ('" & FromDate & "' > JVALUEDATE)  AND ('12/31/2050' >= JDUEDATE) AND ('01/01/1980' <= JDUEDATE) AND ('12/31/2050' >= JDATF3) AND ('01/01/1980' <= JDATF3) AND (0 <> JMSUF) )  AND JTYPE<>1 AND JTYPE <>2 AND ((JSTATUS = 1 AND JTYPE<>1) OR (JSTATUS = 0 AND JTYPE=1)) AND ADUMI <> 3 "

            Dim CreditBalance = " SELECT   cast(  sum( JMSUF ) as decimal(10,2))  as Credit " _
            & " from RPHSTRANSRETRIV" _
            & " WHERE   JMDEBITCREDIT=0 and       ( JMACCOUNTKEY = '" & RecCustNoTextEdit.Text & "'  AND ('" & FromDate & "' > JVALUEDATE)  AND ('12/31/2050' >= JDUEDATE) AND ('01/01/1980' <= JDUEDATE) AND ('12/31/2050' >= JDATF3) AND ('01/01/1980' <= JDATF3) AND (0 <> JMSUF) )  AND JTYPE<>1 AND JTYPE <>2 AND ((JSTATUS = 1 AND JTYPE<>1) OR (JSTATUS = 0 AND JTYPE=1)) AND ADUMI <> 3 "

            sql.WizCountRunQuery(AccountStatmentss)

            GridControl1.DataSource = sql.SQLDS.Tables(0)

            Dim DebitBalanceString As String = "0", CreditBalanceString As String = "0"
            sql.WizCountRunQuery(DebitBalance)
            If Not IsDBNull(sql.SQLDS.Tables(0).Rows(i).Item("Debit")) Then DebitBalanceString = CType(sql.SQLDS.Tables(0).Rows(i).Item("Debit"), String)

            sql.WizCountRunQuery(CreditBalance)
            If Not IsDBNull(sql.SQLDS.Tables(0).Rows(i).Item("Credit")) Then CreditBalanceString = CType(sql.SQLDS.Tables(0).Rows(i).Item("Credit"), String)

            Dim DrBalance, CrBalance As Integer
            DrBalance = 0 : CrBalance = 0
            Dim Balance = CInt(DebitBalanceString) - CInt(CreditBalanceString)
            If Balance >= 0 Then DrBalance = Balance Else CrBalance = -1 * Balance

            GridView1.AddNewRow()
            Dim rowHandle As Integer = GridView1.GetRowHandle(GridView1.DataRowCount)
            If GridView1.IsNewItemRow(rowHandle) Then
                GridView1.SetRowCellValue(rowHandle, GridView1.Columns(0), FromDate)
                GridView1.SetRowCellValue(rowHandle, GridView1.Columns(1), 0)
                GridView1.SetRowCellValue(rowHandle, GridView1.Columns(2), 0)
                GridView1.SetRowCellValue(rowHandle, GridView1.Columns(3), "رصيد مدور")
                GridView1.SetRowCellValue(rowHandle, GridView1.Columns(4), DrBalance)
                GridView1.SetRowCellValue(rowHandle, GridView1.Columns(5), CrBalance)
            End If

            If GridView1.Columns.Count = 7 Then
                GridView1.Columns("ALIAS6F").SortOrder = DevExpress.Data.ColumnSortOrder.Ascending
                GridView1.UpdateCurrentRow()
            Else
                GridView1.Columns("ALIAS6F").SortOrder = DevExpress.Data.ColumnSortOrder.Ascending
                GridView1.UpdateCurrentRow()
                OptimizeGrid()
            End If
        Catch ex As Exception
            Exit Sub
        End Try

    End Sub

    Public Sub OptimizeGrid()
        Dim col As DevExpress.XtraGrid.Columns.GridColumn = GridView1.Columns.AddField("colRunningBalance")
        col.UnboundType = DevExpress.Data.UnboundColumnType.Decimal
        col.VisibleIndex = 7
        col.Caption = "الرصيد"
        col.DisplayFormat.FormatType = DevExpress.Utils.FormatType.Custom
        col.DisplayFormat.FormatString = "{0:#,##0.00}"
        col.Visible = True
    End Sub

    Private Sub GridView1_CustomUnboundColumnData(sender As Object, e As DevExpress.XtraGrid.Views.Base.CustomColumnDataEventArgs) Handles GridView1.CustomUnboundColumnData

        Dim view As DevExpress.XtraGrid.Views.Grid.GridView = TryCast(sender, DevExpress.XtraGrid.Views.Grid.GridView)

        If e.Column.FieldName = "colRunningBalance" Then
            If e.IsGetData Then
                Dim total As Decimal = 0
                Dim rHandle As Integer = view.GetRowHandle(e.ListSourceRowIndex)

                For i As Integer = -1 To (rHandle - 1)
                    total += Convert.ToDecimal(view.GetRowCellValue(i + 1, "ALIAS12F_DEB"))
                    total -= Convert.ToDecimal(view.GetRowCellValue(i + 1, "ALIAS12F_CR"))
                Next

                e.Value = total
            End If
        End If

        GridView1.Columns("ALIAS6F").SortOrder = DevExpress.Data.ColumnSortOrder.Ascending

    End Sub

    Private Sub SimpleButton10_Click(sender As Object, e As EventArgs) Handles SimpleButton10.Click
        AccounStatment(CStr(Format(DateEditFrom.DateTime, "yyyy-MM-dd")), CStr(Format(DateEditTo.DateTime, "yyyy-MM-dd")))

    End Sub

    Private Sub SimpleButton11_Click(sender As Object, e As EventArgs) Handles SimpleButton11.Click
        GridControl1.ShowPrintPreview()
    End Sub

    Private Sub SimpleButton12_Click(sender As Object, e As EventArgs) Handles SimpleButton12.Click
        SqlDataSource1.Queries(0).Parameters(0).Value = Me.RecCustNoTextEdit.Text
        SqlDataSource1.Queries(0).Parameters(1).Value = CStr(Format(DateEdit1.DateTime, "yyyy-MM-dd"))
        SqlDataSource1.Queries(0).Parameters(2).Value = CStr(Format(DateEdit2.DateTime, "yyyy-MM-dd"))
        SqlDataSource1.Fill()
    End Sub

    Private Sub SimpleButton13_Click(sender As Object, e As EventArgs) Handles SimpleButton13.Click

        SqlDataSource1.Queries(0).Parameters(0).Value = Me.RecCustNoTextEdit.Text
        SqlDataSource1.Queries(0).Parameters(1).Value = CDate(DateTime.Now.ToString("yyyy-MM-dd 00:00:00.000"))
        SqlDataSource1.Queries(0).Parameters(2).Value = CDate(DateTime.Now.AddYears(+1000).ToString("yyyy-MM-dd 00:00:00.000"))
        SqlDataSource1.Fill()
    End Sub

    Private Sub RecCustNoTextEdit_EditValueChanged(sender As Object, e As EventArgs) Handles RecCustNoTextEdit.EditValueChanged
        If RecCustNoTextEdit.Text <> "" Then
            RecCustNameTextEdit.Text = GetAccData(Me.RecCustNoTextEdit.Text).FullNamee
        End If
    End Sub

    Private Sub RecCustNoTextEdit_DoubleClick(sender As Object, e As EventArgs) Handles RecCustNoTextEdit.DoubleClick
        '  FinanceSelectAccount.Text = Me.Text
        FinanceSelectAccount.TextEdit1.Text = Me.Name.ToString
        FinanceSelectAccount.Show()
        '    RecCustNoTextEdit.Text = My.Settings.AccID
    End Sub

    Private Sub SimpleButton14_Click(sender As Object, e As EventArgs) Handles SimpleButton14.Click
        SqlDataSource2.Fill()
    End Sub

    Private Sub RecCustNameTextEdit_EditValueChanged(sender As Object, e As EventArgs) Handles RecCustNameTextEdit.EditValueChanged
        TextEdit2.Text = RecCustNameTextEdit.Text
        TextEdit3.Text = RecCustNameTextEdit.Text
    End Sub

    Private Sub NavigationPane1_SelectedPageChanged(sender As Object, e As SelectedPageChangedEventArgs) Handles NavigationPane1.SelectedPageChanged

        Try
            AccounStatment(CStr(Format(DateEditFrom.DateTime, "yyyy-MM-dd")), CStr(Format(DateEditTo.DateTime, "yyyy-MM-dd")))

            SqlDataSource1.Queries(0).Parameters(0).Value = Me.RecCustNoTextEdit.Text
            SqlDataSource1.Queries(0).Parameters(1).Value = CStr(Format(DateEdit1.DateTime, "yyyy-MM-dd"))
            SqlDataSource1.Queries(0).Parameters(2).Value = CStr(Format(DateEdit2.DateTime, "yyyy-MM-dd"))
            SqlDataSource1.Fill()
        Catch ex As Exception
            Exit Sub
        End Try

    End Sub



    Private Sub RecRateSpinEdit_TextChanged(sender As Object, e As EventArgs) Handles RecSmallCurrName.TextChanged
        Write()

        CalcTotal()
    End Sub



    Private Sub ChequeDataDataGridView_CellBeginEdit(sender As Object, e As DataGridViewCellCancelEventArgs)







    End Sub

    Private Sub EndCRMTask()

        Try
            For i = 0 To GridView4.RowCount - 1
                If CType(Me.GridView4.GetRowCellValue(i, "NoteStatus"), String) = "مغلقة" Then
                    Dim TaskID As String = GridView4.GetRowCellValue(i, "TaskID").ToString
                    Dim strDate As String = Date.Now.ToString("yyyy-MM-dd HH:mm:ss.000")
                    Dim sql As New SQLControl
                    Dim SQLUpdateStatus As String = "Update [CRM].[dbo].[CRMTasks]  set [NoteStatus] ='تم التحصيل' , [CloseDate] = CONVERT(DATETIME, '" & strDate & "', 102) , [CloseNote] = 'من سند قبض' where [TaskID]= " & TaskID
                    sql.CRMRunQuery(SQLUpdateStatus)
                End If
            Next

        Catch ex As Exception
            Exit Sub
        End Try

    End Sub


    Private Function CheckCRMTaskCount() As Boolean

        If GridView4.RowCount = 0 Then
            Return False
        Else
            Dim j As Integer = 0
            For i = 0 To GridView4.RowCount - 1
                If CType(Me.GridView4.GetRowCellValue(i, "NoteStatus"), String) = "مفتوحة" Then j = j + 1
            Next

            If j = GridView4.RowCount Then
                Return True
            Else
                Return False
            End If
        End If


    End Function




    Private Sub CheckTasks()

        Dim sql As New SQLControl
        Try
            Dim SqlString As String = "Select  AccrualDate,CustomerName,ToUser,TaskType,Amount,TaskMonth,Note,TaskID, NoteStatus from CRMTasks where CustID = " & RecCustNoTextEdit.Text & "  and NoteStatus = 'مفتوحة' "
            sql.CRMRunQuery(SqlString)
            If sql.SQLDS.Tables(0).Rows.Count = 0 Then Exit Sub

            '  GridControl4.DataSource = sql.SQLDS.Tables(0)
            '  My.Forms.FinancialReceiptUnPaidTasks.GridControl4.DataSource = sql.SQLDS.Tables(0)
        Catch ex As Exception
            MsgBox("خطا مهمة غير موجودة")
        End Try

        Dim forms As New FinancialReceiptUnPaidTasks
        FinancialReceiptUnPaidTasks.Visible = False
        forms.GridControl4.DataSource = sql.SQLDS.Tables(0)
        forms.ShowDialog()


        '  RepositoryItemCheckEdit1.ValueChecked = True
        '   GridView4.SetRowCellValue(0, "State", True)
        '   GridView4.SetRowCellValue(1, GridView4.Columns("State"), 1)
    End Sub

    Private Sub PanelControl3_Paint(sender As Object, e As PaintEventArgs)

    End Sub

    Private Sub TextEdit1_EditValueChanged(sender As Object, e As EventArgs) Handles TextEdit1.EditValueChanged

    End Sub

    Private Sub RepositoryItemCheckEdit1_Click(sender As Object, e As EventArgs)

    End Sub

    Private Sub RecCustNoTextEdit_Leave(sender As Object, e As EventArgs) Handles RecCustNoTextEdit.Leave
        If RecCustNoTextEdit.Text <> "" Then
            ' CheckTasks()
            TextEditAccChequesTotal.EditValue = GetSumCheks(CStr(DateTime.Now.ToString("yyyy-MM-dd 00:00:00.000")), RecCustNoTextEdit.Text)
            TextEditAccChequeNO.EditValue = GetCountCheks(CStr(DateTime.Now.ToString("yyyy-MM-dd 00:00:00.000")), RecCustNoTextEdit.Text)
            TextEditAccountBalance.EditValue = GetAccBalance(CStr(Format(Today, "yyyy-MM-dd")), RecCustNoTextEdit.Text)
        End If
    End Sub

    Private Sub RecCashSpinEdit_TextChanged_1(sender As Object, e As EventArgs) Handles RecCashSpinEdit.TextChanged
        Write()

        CalcTotal()
    End Sub

    Private Sub RecChequeSpinEdit_TextChanged_1(sender As Object, e As EventArgs) Handles RecChequeSpinEdit.TextChanged
        Write()

        CalcTotal()
    End Sub

    Private Sub RecOtherSpinEdit_TextChanged_1(sender As Object, e As EventArgs) Handles RecOtherSpinEdit.TextChanged
        Write()

        CalcTotal()
    End Sub

    Private Sub RecTotalSpinEdit_TextChanged_1(sender As Object, e As EventArgs) Handles RecTotalSpinEdit.TextChanged
        Write()

        CalcTotal()
    End Sub

    Private Sub SimpleButton16_Click(sender As Object, e As EventArgs) Handles SimpleButton16.Click
        GridControl2.ShowPrintPreview()
    End Sub

    'Private Function GetAccBalance(ToDate As String) As Integer

    '    Dim DebitBalance = " SELECT   cast(  sum( JMSUF ) as decimal(10,2)) as Debit    " _
    '    & " from RPHSTRANSRETRIV" _
    '    & " WHERE   JMDEBITCREDIT=1 and       ( JMACCOUNTKEY = '" & RecCustNoTextEdit.Text & "'  AND ('" & ToDate & "' > JVALUEDATE)  AND ('12/31/2050' >= JDUEDATE) AND ('01/01/1980' <= JDUEDATE) AND ('12/31/2050' >= JDATF3) AND ('01/01/1980' <= JDATF3) AND (0 <> JMSUF) )  AND JTYPE<>1 AND JTYPE <>2 AND ((JSTATUS = 1 AND JTYPE<>1) OR (JSTATUS = 0 AND JTYPE=1)) AND ADUMI <> 3 "

    '    Dim CreditBalance = " SELECT   cast(  sum( JMSUF ) as decimal(10,2))  as Credit " _
    '    & " from RPHSTRANSRETRIV" _
    '    & " WHERE   JMDEBITCREDIT=0 and       ( JMACCOUNTKEY = '" & RecCustNoTextEdit.Text & "'  AND ('" & ToDate & "' > JVALUEDATE)  AND ('12/31/2050' >= JDUEDATE) AND ('01/01/1980' <= JDUEDATE) AND ('12/31/2050' >= JDATF3) AND ('01/01/1980' <= JDATF3) AND (0 <> JMSUF) )  AND JTYPE<>1 AND JTYPE <>2 AND ((JSTATUS = 1 AND JTYPE<>1) OR (JSTATUS = 0 AND JTYPE=1)) AND ADUMI <> 3 "

    '    Dim DebitBalanceString As String = "0", CreditBalanceString As String = "0"
    '    sql.WizCountRunQuery(DebitBalance)
    '    If Not IsDBNull(sql.SQLDS.Tables(0).Rows(i).Item("Debit")) Then DebitBalanceString = CType(sql.SQLDS.Tables(0).Rows(i).Item("Debit"), String)

    '    sql.WizCountRunQuery(CreditBalance)
    '    If Not IsDBNull(sql.SQLDS.Tables(0).Rows(i).Item("Credit")) Then CreditBalanceString = CType(sql.SQLDS.Tables(0).Rows(i).Item("Credit"), String)

    '    GetAccBalance = CInt(DebitBalanceString) - CInt(CreditBalanceString) - CInt(AmountInNisText.EditValue)

    '    'Dim DrBalance, CrBalance As Integer
    '    'DrBalance = 0 : CrBalance = 0
    '    'GetAccBalance = CInt(DebitBalanceString) - CInt(CreditBalanceString)
    '    'If GetAccBalance >= 0 Then DrBalance = GetAccBalance Else CrBalance = -1 * GetAccBalance

    '    Return GetAccBalance

    'End Function

    Private Function GetAccBalance(ToDate As String, AccNo As String) As Integer

        Try

            Dim sql As New SQLControl
            Dim i As Integer
            Dim DebitBalance = " SELECT   cast(  sum( JMSUF ) as decimal(10,2)) as Debit    " _
            & " from RPHSTRANSRETRIV" _
            & " WHERE   JMDEBITCREDIT=1 and       ( JMACCOUNTKEY = '" & AccNo & "'  AND ('" & ToDate & "' > JVALUEDATE)  AND ('12/31/2050' >= JDUEDATE) AND ('01/01/1980' <= JDUEDATE) AND ('12/31/2050' >= JDATF3) AND ('01/01/1980' <= JDATF3) AND (0 <> JMSUF) )  AND JTYPE<>1 AND JTYPE <>2 AND ((JSTATUS = 1 AND JTYPE<>1) OR (JSTATUS = 0 AND JTYPE=1)) AND ADUMI <> 3 "

            Dim CreditBalance = " SELECT   cast(  sum( JMSUF ) as decimal(10,2))  as Credit " _
            & " from RPHSTRANSRETRIV" _
            & " WHERE   JMDEBITCREDIT=0 and       ( JMACCOUNTKEY = '" & AccNo & "'  AND ('" & ToDate & "' > JVALUEDATE)  AND ('12/31/2050' >= JDUEDATE) AND ('01/01/1980' <= JDUEDATE) AND ('12/31/2050' >= JDATF3) AND ('01/01/1980' <= JDATF3) AND (0 <> JMSUF) )  AND JTYPE<>1 AND JTYPE <>2 AND ((JSTATUS = 1 AND JTYPE<>1) OR (JSTATUS = 0 AND JTYPE=1)) AND ADUMI <> 3 "

            Dim DebitBalanceString As String = "0", CreditBalanceString As String = "0"
            sql.WizCountRunQuery(DebitBalance)
            If Not IsDBNull(sql.SQLDS.Tables(0).Rows(i).Item("Debit")) Then DebitBalanceString = CType(sql.SQLDS.Tables(0).Rows(i).Item("Debit"), String)

            sql.WizCountRunQuery(CreditBalance)
            If Not IsDBNull(sql.SQLDS.Tables(0).Rows(i).Item("Credit")) Then CreditBalanceString = CType(sql.SQLDS.Tables(0).Rows(i).Item("Credit"), String)

            GetAccBalance = CInt(DebitBalanceString) - CInt(CreditBalanceString)

            Return GetAccBalance
        Catch ex As Exception

        End Try

        Return GetAccBalance

    End Function


    'Private Sub GetCheqs()
    '    Dim DebitBalance = " SELECT   cast(  sum( JMSUF ) as decimal(10,2)) as Debit    " _
    '    & " from RPHSTRANSRETRIV" _
    '    & " WHERE   JMDEBITCREDIT=1 and       ( JMACCOUNTKEY = '" & RecCustNoTextEdit.Text & "'  AND ('" & Format(Today, "yyyy-MM-dd") & "' > JVALUEDATE)  AND ('12/31/2050' >= JDUEDATE) AND ('01/01/1980' <= JDUEDATE) AND ('12/31/2050' >= JDATF3) AND ('01/01/1980' <= JDATF3) AND (0 <> JMSUF) )  AND JTYPE<>1 AND JTYPE <>2 AND ((JSTATUS = 1 AND JTYPE<>1) OR (JSTATUS = 0 AND JTYPE=1)) AND ADUMI <> 3 "
    '    sql.WizCountRunQuery(DebitBalance)
    '    If Not IsDBNull(sql.SQLDS.Tables(0).Rows(i).Item("Debit")) Then DebitBalanceString = CType(sql.SQLDS.Tables(0).Rows(i).Item("Debit"), String)
    'End Sub

    Private Sub RecCashSpinEdit_EditValueChanged_1(sender As Object, e As EventArgs) Handles RecCashSpinEdit.EditValueChanged

    End Sub

    Private Sub RecCurrRate_EditValueChanged(sender As Object, e As EventArgs) Handles RecCurrRate.EditValueChanged
        Write()

        CalcTotal()
    End Sub

    Private Sub RecNoteTextEdit_EditValueChanged(sender As Object, e As EventArgs) Handles RecNoteTextEdit.EditValueChanged

    End Sub

    Private Sub RecNoteTextEdit_Leave(sender As Object, e As EventArgs) Handles RecNoteTextEdit.Leave
        Try
            If CDec(RecChequeSpinEdit.Text) = 0 Or RecChequeSpinEdit.Text = "" Then SimpleButton1.Select()
        Catch ex As Exception

        End Try

    End Sub

    Private Function GetSumCheks(FromDate As String, AccNo As String) As Integer

        Try
            Dim sql As New SQLControl
            Dim i As Integer

            Dim SqlString As String = "SELECT Sum(NIS) as NIS2
                                    FROM
                                    (  SELECT  CASE WHEN SuFDlr= 0 THEN SuF else SuFDlr END AS NIS
		                            FROM [ALHUDA].[dbo].[Cheqs]
		                            where AccKey='" & AccNo & "' and ValueDate > '" & FromDate & "' ) as TotalNis"

            sql.WizCountRunQuery(SqlString)
            If Not IsDBNull(sql.SQLDS.Tables(0).Rows(i).Item("NIS2")) Then GetSumCheks = CType(sql.SQLDS.Tables(0).Rows(i).Item("NIS2"), Integer)

            Return GetSumCheks
        Catch ex As Exception

        End Try

        Return GetSumCheks

    End Function

    Private Function GetCountCheks(FromDate As String, AccNo As String) As Integer

        Try
            Dim sql As New SQLControl
            Dim i As Integer

            Dim SqlString As String = "SELECT Count(NIS) as NIS2
                                    FROM
                                    (  SELECT  CASE WHEN SuFDlr= 0 THEN SuF else SuFDlr END AS NIS
		                            FROM [ALHUDA].[dbo].[Cheqs]
		                            where AccKey='" & AccNo & "' and ValueDate > '" & FromDate & "' ) as TotalNis"

            sql.WizCountRunQuery(SqlString)
            If Not IsDBNull(sql.SQLDS.Tables(0).Rows(i).Item("NIS2")) Then GetCountCheks = CType(sql.SQLDS.Tables(0).Rows(i).Item("NIS2"), Integer)
        Catch ex As Exception

        End Try

        Return GetCountCheks

    End Function

    Private Sub ChequeDataDataGridView_CellContentClick(sender As Object, e As DataGridViewCellEventArgs)

    End Sub

    Private Sub SimpleButton17_Click(sender As Object, e As EventArgs) Handles SimpleButton17.Click
        Me.ReceiptDataTableAdapter.FillBy(Me.CRMDataSet.ReceiptData, (CType(RecNOSpinEdit.Text, Integer)))
        Me.ChequeDataTableAdapter.FillBy(Me.CRMDataSet.ChequeData, (CType(RecNOSpinEdit.Text, Integer)))
    End Sub

    Private Sub ChequeDataDataGridView_Validated(sender As Object, e As EventArgs)

    End Sub

    Private Sub ChequeDataGridControl_Click(sender As Object, e As EventArgs) Handles ChequeDataGridControl.Click

    End Sub

    Private Sub GridView5_InitNewRow(ByVal sender As Object, ByVal e As DevExpress.XtraGrid.Views.Grid.InitNewRowEventArgs) Handles GridView5.InitNewRow

        Try
            With Me.GridView5
                ' .SetRowCellValue(e.RowHandle, "ChequeAccDate", Today)
                .SetRowCellValue(e.RowHandle, "ChequeAmount", "0")
                .SetRowCellValue(e.RowHandle, "ChequeReceiptNo", RecNOSpinEdit.Text)
                ' .SetRowCellValue(e.RowHandle, "ChequeBank", Me.GridView5.GetRowCellValue(GridView5.FocusedRowHandle - 1, "ChequeBank"))
            End With
        Catch ex As Exception
            MsgBox(ex.ToString)
        End Try

        Try
            Dim lastRowHandle = GridView5.DataRowCount - 1
            If Not GridView5.IsValidRowHandle(lastRowHandle) Then Return

            GridView5.SetRowCellValue(e.RowHandle, colChequeNO,
                                     CInt(GridView5.GetRowCellValue(lastRowHandle, colChequeNO)) + 1)

            GridView5.SetRowCellValue(e.RowHandle, colChequeBank,
                                      GridView5.GetRowCellValue(lastRowHandle, colChequeBank))

            GridView5.SetRowCellValue(e.RowHandle, colChequeBranch,
                                      GridView5.GetRowCellValue(lastRowHandle, colChequeBranch))

            GridView5.SetRowCellValue(e.RowHandle, colChequeAccount,
                          GridView5.GetRowCellValue(lastRowHandle, colChequeAccount))

            GridView5.SetRowCellValue(e.RowHandle, colChequeAmount,
                          GridView5.GetRowCellValue(lastRowHandle, colChequeAmount))

            Dim AccDate As String = CStr(GridView5.GetRowCellValue(lastRowHandle, colChequeAccDate))
            GridView5.SetRowCellValue(e.RowHandle, colChequeAccDate, CDate(AccDate).AddMonths(1))

        Catch ex As Exception

        End Try
    End Sub

    Private Sub GridView5_CellValueChanged(sender As Object, e As CellValueChangedEventArgs) Handles GridView5.CellValueChanged
        'Dim view As GridView = TryCast(sender, GridView)
        'If view Is Nothing Then Return
        'If e.Column.Caption <> "ChequeAmount" Then Return
        'RecChequeSpinEdit.Text = CStr(colChequeAmount.SummaryItem.SummaryValue)
        ' MsgBox(CStr(colChequeAmount.SummaryItem.SummaryValue))
    End Sub

    Private Sub GridView5_RowUpdated(sender As Object, e As RowObjectEventArgs) Handles GridView5.RowUpdated
        RecChequeSpinEdit.Text = CStr(colChequeAmount.SummaryItem.SummaryValue)
    End Sub

    Private Sub GridView5_CellValueChanging(sender As Object, e As CellValueChangedEventArgs) Handles GridView5.CellValueChanging
        'Dim view As GridView = TryCast(sender, GridView)
        'If view Is Nothing Then Return
        'If e.Column.Caption <> "ChequeAmount" Then Return
        'RecChequeSpinEdit.Text = CStr(colChequeAmount.SummaryItem.SummaryValue)
    End Sub

    Private Sub GridView5_KeyPress(sender As Object, e As KeyPressEventArgs) Handles GridView5.KeyPress
        RecChequeSpinEdit.Text = CStr(colChequeAmount.SummaryItem.SummaryValue)
    End Sub

    Private Sub GridView5_CustomRowCellEdit(sender As Object, e As CustomRowCellEditEventArgs) Handles GridView5.CustomRowCellEdit
        RecChequeSpinEdit.Text = (CStr(colChequeAmount.SummaryItem.SummaryValue))
    End Sub
End Class