Public Class FinancialTransDet

    Sub New()

        InitializeComponent()
        ' This line of code is generated by Data Source Configuration Wizard
        ' Fill a SqlDataSource
        SqlDataSource1.Fill()
    End Sub

    Private Sub FinancialTransDet_Load(sender As Object, e As EventArgs) Handles MyBase.Load

    End Sub

End Class