Imports DevExpress.Utils
Imports DevExpress.XtraGrid.Views.Grid

Public Class ReceiptsAudit

    Sub New()

        InitializeComponent()

        ' This line of code is generated by Data Source Configuration Wizard
        ' Fill a SqlDataSource
        ' SqlDataSource2.Fill()
        ' This line of code is generated by Data Source Configuration Wizard
        ' Fill a SqlDataSource
        '    SqlDataSource2.Fill()
    End Sub

    Private Sub ReceiptsAudit_Load(sender As Object, e As EventArgs) Handles MyBase.Load

        Try
            Me.UsersTableAdapter.Fill(Me.CRMDataSet.Users)
            '  Me.UsersTableAdapter.FillBy(Me.CRMDataSet.Users, My.Settings.UserName)
            '  LookUpEdit1.EditValue = 1
            LookUpEdit1.EditValue = GlobalVariables.UserIDInteger
            '  LookUpEdit1.EditValue = LookUpEdit1.Properties.GetKeyValueByDisplayText("1800013")
            '  UpdateAll()
            '   SqlDataSource1.Queries(0).Parameters(0).Value = My.Settings.UserName
            '   SqlDataSource1.Fill()
        Catch ex As System.Exception
            System.Windows.Forms.MessageBox.Show(ex.Message)
        End Try

    End Sub

    Private Sub GetUserID()

    End Sub

    Private Sub SimpleButton1_Click(sender As Object, e As EventArgs) Handles SimpleButton1.Click, SimpleButton1.Click
        UpdateAll()
    End Sub

    Sub UpdateAll()

        Try
            Dim row As Object = LookUpEdit1.Properties.GetDataSourceRowByKeyValue(LookUpEdit1.EditValue)
            Dim aa As String = TryCast(row, DataRowView)("userid").ToString()
            If aa = "" Then MsgBox("الرجاء اختيار الموظف") : Exit Sub
            SqlDataSource1.Queries(0).Parameters(0).Value = aa
            SqlDataSource1.Fill()

            Dim row2 As Object = LookUpEdit1.Properties.GetDataSourceRowByKeyValue(LookUpEdit1.EditValue)
            Dim aa2 As String = TryCast(row2, DataRowView)("userid").ToString()
            SqlDataSource2.Queries(0).Parameters(0).Value = aa2
            SqlDataSource2.Fill()

            GridControl1.ForceInitialize()
            GridView1.BestFitColumns()
            GridControl2.ForceInitialize()
            GridView2.BestFitColumns()
        Catch ex As Exception
            MsgBox("خطا",, "UpdateAll")
        End Try

    End Sub

    Private Sub Transfer(RecNo As String, UserID As String)

        Dim sql As New SQLControl
        Try
            Dim SQLString As String = " update  [ReceiptData] Set RecOwner = '" & UserID & "', RecAudit=0  where RecNo = '" & RecNo & "'"
            sql.CRMRunQuery(SQLString)
            UpdateAll()
        Catch
            MsgBox("خطا")
        End Try
    End Sub

    Private Sub SimpleButton2_Click(sender As Object, e As EventArgs) Handles SimpleButton2.Click

        Try
            If LookUpEdit2.Text = String.Empty Then MsgBox("يجب اختيار حساب الذي سيتم تحويل العهدة له") : Exit Sub
            If GridView2.DataRowCount = 0 Then MsgBox("لا يوجد بيانات للترحيل") : Exit Sub
            Dim row As Object = LookUpEdit2.Properties.GetDataSourceRowByKeyValue(LookUpEdit2.EditValue)
            Dim aa As String = TryCast(row, DataRowView)("userid").ToString()
            For i As Integer = 0 To GridView2.RowCount - 1
                Dim RecNO As String = CType(GridView2.GetRowCellValue(i, "RecNO"), String)
                Transfer(RecNO, aa)
            Next
        Catch ex As Exception
            MsgBox("خطا")
        End Try
        UpdateAll()
    End Sub

    Private Sub LookUpEdit1_EditValueChanged(sender As Object, e As EventArgs) Handles LookUpEdit1.EditValueChanged
        UpdateAll()
    End Sub

    Private Sub AuditCol_ButtonClick(sender As Object, e As DevExpress.XtraEditors.Controls.ButtonPressedEventArgs) Handles AuditCol.ButtonClick

        Dim sql As New SQLControl
        Dim CardID As Integer = CInt(GridView1.GetRowCellValue(GridView1.FocusedRowHandle, "RecNO"))

        Try

            Dim SQLString As String = " update  [ReceiptData] Set RecAudit = 2  where RecNo = " & CardID
            sql.CRMRunQuery(SQLString)
            UpdateAll()
        Catch
            MsgBox("خطا")
        End Try
    End Sub

    Private Sub ReAuditButton_ButtonClick(sender As Object, e As DevExpress.XtraEditors.Controls.ButtonPressedEventArgs)

        Dim sql As New SQLControl
        Dim CardID As Integer = CInt(GridView2.GetRowCellValue(GridView2.FocusedRowHandle, "RecNO"))

        Try

            Dim SQLString As String = " update  [ReceiptData] Set RecAudit = 0  where RecNo = " & CardID
            sql.CRMRunQuery(SQLString)
            UpdateAll()
        Catch
            MsgBox("خطا")
        End Try
    End Sub

    Private Sub RepositoryItemButtonEdit1_Click(sender As Object, e As EventArgs) Handles RepositoryItemButtonEdit1.Click
        Dim sql As New SQLControl
        Dim CardID As Integer = CInt(GridView2.GetRowCellValue(GridView2.FocusedRowHandle, "RecNO"))

        Try

            Dim SQLString As String = " update  [ReceiptData] Set RecAudit = 0  where RecNo = " & CardID
            sql.CRMRunQuery(SQLString)
            UpdateAll()
        Catch
            MsgBox("خطا")
        End Try
    End Sub

End Class