Public Class PrintingAllJobs
    Sub New()

        InitializeComponent()
        ' This line of code is generated by Data Source Configuration Wizard
        ' Fill a SqlDataSource
        SqlDataSource1.Queries(0).Parameters(0).Value = JobStatusTextEdit.Text
        SqlDataSource1.Fill()
    End Sub

    Private Sub PrintingSystemJobsBindingNavigatorSaveItem_Click(sender As Object, e As EventArgs)
    End Sub

    Private Sub PrintingAllJobs_Load(sender As Object, e As EventArgs) Handles MyBase.Load
        RefreshData()
    End Sub

    Private Sub RefreshData()
        SqlDataSource1.Queries(0).Parameters(0).Value = JobStatusTextEdit.Text
        SqlDataSource1.Fill()
        GridView1.BestFitColumns()


    End Sub

    Private Sub SimpleButton1_Click(sender As Object, e As EventArgs) Handles SimpleButton1.Click
        RefreshData()
    End Sub

    Private Sub SimpleButton2_Click(sender As Object, e As EventArgs) Handles SimpleButton2.Click
        My.Forms.PrintingJobs.PrintingSystemJobsBindingSource.AddNew()
        My.Forms.PrintingJobs.JobIDTextEdit.Text = "-1"
        My.Forms.PrintingJobs.Show()
    End Sub

    Private Sub PrintingSystemJobsGridControl_Click(sender As Object, e As EventArgs) Handles PrintingSystemJobsGridControl.Click


    End Sub

    Private Sub RepositoryItemOpenJob_ButtonClick(sender As Object, e As DevExpress.XtraEditors.Controls.ButtonPressedEventArgs) Handles RepositoryItemOpenJob.ButtonClick
        My.Forms.PrintingJobs.TextEditJobID.Text = CStr(GridView1.GetRowCellValue(GridView1.FocusedRowHandle, "JobID"))
        My.Forms.PrintingJobs.Show()
    End Sub

    Private Sub ComboBoxEdit1_SelectedIndexChanged(sender As Object, e As EventArgs)

    End Sub
End Class