Imports DevExpress.XtraBars.Alerter
Imports DevExpress.XtraGrid.Views.Grid
Imports DevExpress.XtraGrid.Views.Base
Imports DevExpress.XtraGrid.Views.BandedGrid

Public Class CRMTasks

    Sub New()

        InitializeComponent()

        ' This line of code is generated by Data Source Configuration Wizard
        ' Fill a SqlDataSource
        '    SqlDataSource1.Fill()
        ' This line of code is generated by Data Source Configuration Wizard
        ' Fill a SqlDataSource
        '    SqlDataSource1.Fill()
    End Sub

    Private Sub CRMTasks_Load(sender As Object, e As EventArgs) Handles MyBase.Load
        TaskMonthText.Text = Format(Today.AddMonths(-1), "yyyyMM")
        'TODO: This line of code loads data into the 'CRMDataSet.Users' table. You can move, or remove it, as needed.
        Me.UsersTableAdapter.Fill(Me.CRMDataSet.Users)

        LookUpEdit1.EditValue = My.Settings.UserName

        'Dim TaskMonth As Integer = CInt(Format(Today, "MM"))

        'If TaskMonth <> 1 Then TaskMonth = TaskMonth - 1 Else TaskMonth = 12
        'If TaskMonth = 1 Then TaskMonth = 12

        'Me.TaskMonthText.Text = CType(TaskMonth, String)
        Dim TaskMonth As String = TaskMonthText.Text

        Me.TaskStatusText.Text = "مفتوحة"
        Me.TaskTypeCombo.Text = "دين" '

        LoadData(My.Settings.UserName, CStr(TaskMonth), Me.TaskStatusText.Text, Me.TaskTypeCombo.Text)

        Percentage()

        'Dim i As Integer
        'For i = 1 To GridView1.Columns.Count - 5
        '    Dim col As DevExpress.XtraGrid.Columns.GridColumn = Me.GridView1.Columns(i)
        '    col.OptionsColumn.AllowEdit = False
        '    col.OptionsColumn.AllowFocus = False
        'Next

        '  Me.MobileText.Text = "0597505029"

        GetImage()

    End Sub

    Private Sub Percentage()

        Try
            Dim no1 As Integer = CInt(TextEdit2.Text)
            Dim no2 As Integer = CInt(TextEdit3.Text)

            TextEdit4.EditValue = Format(no1 / no2, "0%")
        Catch ex As Exception

        End Try

    End Sub

    Private Sub RepositoryItemButtonEdit1_ButtonClick(sender As Object, e As DevExpress.XtraEditors.Controls.ButtonPressedEventArgs)

        Dim strDate As String = Date.Now.ToString("yyyy-MM-dd HH:mm:ss.000")

        '      MsgBox(CloseDate.ToString)
        Dim CustName As String = CType(Me.GridView1.GetRowCellValue(GridView1.FocusedRowHandle, "CustomerName"), String)
        Dim ACCNAME As String = "هل تم تحصيل الزبون :   " & CustName
        Dim result As DialogResult = DevExpress.XtraEditors.XtraMessageBox.Show(ACCNAME, "تأكيد", MessageBoxButtons.YesNo)

        If result = System.Windows.Forms.DialogResult.Yes Then
            '      Try

            AddEvents("تنبيه", "  تم تحصيل الزبون " & " " & CustName, Me.Text, "1800013", My.Settings.UserName, "True")
            AddEvents("تنبيه", "  تم تحصيل الزبون " & " " & CustName, Me.Text, "1800013", My.Settings.UserName, "True")
            AddEvents("تنبيه", "  تم تحصيل الزبون " & " " & CustName, Me.Text, "1800013", My.Settings.UserName, "True")

            Dim TaskID As String = CType(Me.GridView1.GetRowCellValue(GridView1.FocusedRowHandle, "TaskID"), String)

            Dim sql As New SQLControl
            Dim SQLUpdateStatus As String = "Update [CRM].[dbo].[CRMTasks]  set [NoteStatus] ='تم التحصيل' , CloseNote='تم التحصيل' where [TaskID]= " & TaskID
            sql.CRMRunQuery(SQLUpdateStatus)

            Dim sql2 As New SQLControl
            Dim SQLUpdateDate As String = "Update [CRM].[dbo].[CRMTasks]  set [CloseDate] = CONVERT(DATETIME, '" & strDate & "', 102) where [TaskID]= " & TaskID
            sql2.CRMRunQuery(SQLUpdateDate)

            AddEvents("تنبيه", "  تم تحصيل الزبون " & " " & CustName, Me.Text, "1800013", My.Settings.UserName, "True")
            AddEvents("تنبيه", "  تم تحصيل الزبون " & " " & CustName, Me.Text, "1800013", My.Settings.UserName, "True")
            AddEvents("تنبيه", "  تم تحصيل الزبون " & " " & CustName, Me.Text, "1800013", My.Settings.UserName, "True")

            If CType(Global.DevExpress.XtraEditors.XtraMessageBox.Show(CType("تم تحصيل واغلاق المهمة، هل تريد ارسال رسالة الى المحصل", String), CType("تأكيد", String), CType(Global.System.Windows.Forms.MessageBoxButtons.YesNo, Global.System.Windows.Forms.MessageBoxButtons)), Global.System.Windows.Forms.DialogResult) = Global.System.Windows.Forms.DialogResult.Yes Then
                Dim msg As String = DevExpress.XtraEditors.XtraInputBox.Show("ملاحظة المحصل", " ادخل ملاحظات للمحصل حول دفعة الزبون", "")
                FunSendSmS2(Me.MobileText.Text, "شيك جاهز" & " " & CustName & " " & msg & " :" & My.Settings.UserName)
            Else
                MsgBox("لم يتم ارسال رسالة")
            End If

            SqlDataSource1.Fill()
            '  Catch ex As Exception

            '   End Try
        Else
            Exit Sub
        End If

    End Sub

    Private Sub RepositoryItemButtonEdit2_Click(sender As Object, e As EventArgs) Handles RepositoryItemButtonEdit2.Click

        '  MsgBox("تم التاجيل")
        Dim forms As New CRMEditTaskDate
        CRMEditTaskDate.Visible = False
        With forms
            .TextEdit1.Text = CType(Me.GridView1.GetRowCellValue(GridView1.FocusedRowHandle, "Note"), String)
            .LookUpEdit1.EditValue = Me.LookUpEdit1.EditValue
            .DateEdit1.EditValue = Me.GridView1.GetRowCellValue(GridView1.FocusedRowHandle, "AccrualDate")
            .TaskIDText.Text = CStr(Me.GridView1.GetRowCellValue(GridView1.FocusedRowHandle, "TaskID"))
            .CustomerNameText.Text = CStr(Me.GridView1.GetRowCellValue(GridView1.FocusedRowHandle, "CustomerName"))
            .CustomerCodeText.Text = CStr(Me.GridView1.GetRowCellValue(GridView1.FocusedRowHandle, "CustID"))
            .OwnUserTextEdit.Text = CType(Me.LookUpEdit1.EditValue, String)
        End With
        forms.ShowDialog()

        'My.Forms.CRMEditTaskDate.TextEdit1.Text = CType(Me.GridView1.GetRowCellValue(GridView1.FocusedRowHandle, "Note"), String)
        'My.Forms.CRMEditTaskDate.LookUpEdit1.EditValue = Me.LookUpEdit1.EditValue
        'My.Forms.CRMEditTaskDate.DateEdit1.EditValue = Me.GridView1.GetRowCellValue(GridView1.FocusedRowHandle, "AccrualDate")
        'My.Forms.CRMEditTaskDate.TaskIDText.Text = CStr(Me.GridView1.GetRowCellValue(GridView1.FocusedRowHandle, "TaskID"))
        'My.Forms.CRMEditTaskDate.CustomerNameText.Text = CStr(Me.GridView1.GetRowCellValue(GridView1.FocusedRowHandle, "CustomerName"))
        'My.Forms.CRMEditTaskDate.CustomerCodeText.Text = CStr(Me.GridView1.GetRowCellValue(GridView1.FocusedRowHandle, "CustID"))
        'My.Forms.CRMEditTaskDate.OwnUserTextEdit.Text = CType(Me.LookUpEdit1.EditValue, String)

        'CRMEditTaskDate.Show()

        '  LoadData(My.Settings.UserName, CStr(Me.TaskMonthText.Text), Me.TaskStatusText.Text, Me.TaskTypeCombo.Text)

        '   InputBox("Write the key", "Any title", "Your username goes here!")

    End Sub

    Private Sub SimpleButton1_Click(sender As Object, e As EventArgs) Handles SimpleButton1.Click
        Try

            Dim aa2 As String = ""
            Dim row2 As Object = LookUpEdit1.Properties.GetDataSourceRowByKeyValue(LookUpEdit1.EditValue)

            aa2 = TryCast(row2, DataRowView)("userid").ToString()

            LoadData(aa2, TaskMonthText.Text, TaskStatusText.Text, TaskTypeCombo.Text)
        Catch ex As Exception
            MsgBox("خطأ")
        End Try

    End Sub

    Sub LoadData(UserID As String, TaskMonth As String, TaskStatus As String, TaskType As String)

        SqlDataSource1.Queries(0).Parameters(0).Value = UserID
        SqlDataSource1.Queries(0).Parameters(1).Value = TaskMonth
        SqlDataSource1.Queries(0).Parameters(2).Value = TaskStatus
        SqlDataSource1.Queries(0).Parameters(3).Value = TaskType

        SqlDataSource1.Queries(1).Parameters(0).Value = UserID
        SqlDataSource1.Queries(1).Parameters(1).Value = TaskMonth
        SqlDataSource1.Queries(1).Parameters(2).Value = "مفتوحة"
        SqlDataSource1.Queries(1).Parameters(3).Value = TaskType

        SqlDataSource1.Queries(2).Parameters(0).Value = UserID
        SqlDataSource1.Queries(2).Parameters(1).Value = TaskMonth
        SqlDataSource1.Queries(2).Parameters(2).Value = "تم التحصيل"
        SqlDataSource1.Queries(2).Parameters(3).Value = TaskType

        SqlDataSource1.Queries(3).Parameters(0).Value = UserID
        SqlDataSource1.Queries(3).Parameters(1).Value = TaskMonth
        SqlDataSource1.Queries(3).Parameters(2).Value = TaskType

        SqlDataSource1.Queries(4).Parameters(0).Value = UserID
        SqlDataSource1.Queries(4).Parameters(1).Value = TaskMonth
        SqlDataSource1.Queries(4).Parameters(2).Value = "تم التحصيل"
        SqlDataSource1.Queries(4).Parameters(3).Value = Date.Now.ToString("yyyy-MM-dd")
        SqlDataSource1.Queries(4).Parameters(4).Value = TaskType

        SqlDataSource1.Queries(5).Parameters(0).Value = UserID
        SqlDataSource1.Queries(5).Parameters(1).Value = TaskMonth
        SqlDataSource1.Queries(5).Parameters(2).Value = "مغلقة"
        SqlDataSource1.Queries(5).Parameters(4).Value = TaskType

        SqlDataSource1.Queries(6).Parameters(0).Value = UserID
        SqlDataSource1.Queries(6).Parameters(1).Value = TaskMonth
        SqlDataSource1.Queries(6).Parameters(2).Value = "مفتوحة"
        '   SqlDataSource1.Queries(6).Parameters(3).Value = Date.Now.ToString("yyyy-MM-dd")
        SqlDataSource1.Queries(6).Parameters(3).Value = TaskType

        SqlDataSource1.Fill()

        Percentage()

        CreatTableSummery()

    End Sub

    Private Sub RepositoryItemButtonEdit3_ButtonClick(sender As Object, e As DevExpress.XtraEditors.Controls.ButtonPressedEventArgs) Handles RepositoryItemButtonEdit3.ButtonClick
        'My.Forms.FinancialAccountsDet.AccountKeyTextEdit.Text = CType(Me.GridView1.GetRowCellValue(GridView1.FocusedRowHandle, "CustID"), String)
        'My.Forms.FinancialAccountsDet.SqlDataSource1.Queries(0).Parameters(0).Value = CType(Me.GridView1.GetRowCellValue(GridView1.FocusedRowHandle, "CustID"), String)
        'My.Forms.FinancialAccountsDet.SqlDataSource1.Fill()
        'My.Forms.FinancialAccountsDet.FullNameTextEdit.Select()
        'FinancialAccountsDet.Show()
        My.Forms.FinanceAccDetails.TextEditAccountKey.Text = CType(Me.GridView1.GetRowCellValue(GridView1.FocusedRowHandle, "CustID"), String)
        FinanceAccDetails.ShowDialog()


    End Sub

    Private Sub RepositoryItemButtonEdit3_Click(sender As Object, e As EventArgs) Handles RepositoryItemButtonEdit3.Click

    End Sub

    Private Sub LookUpEdit1_EditValueChanged(sender As Object, e As EventArgs) Handles LookUpEdit1.EditValueChanged
        Dim UserID As String
        Dim row2 As Object = LookUpEdit1.Properties.GetDataSourceRowByKeyValue(LookUpEdit1.EditValue)
        UserID = TryCast(row2, DataRowView)("userid").ToString()

        LoadData(UserID, CStr(TaskMonthText.Text), Me.TaskStatusText.Text, TaskTypeCombo.Text)
    End Sub

    Private Sub TaskMonthText_EditValueChanged(sender As Object, e As EventArgs) Handles TaskMonthText.EditValueChanged
        Try
            Dim UserID As String
            Dim row2 As Object = LookUpEdit1.Properties.GetDataSourceRowByKeyValue(LookUpEdit1.EditValue)
            UserID = TryCast(row2, DataRowView)("userid").ToString()

            LoadData(UserID, CStr(TaskMonthText.Text), Me.TaskStatusText.Text, TaskTypeCombo.Text)
        Catch ex As Exception

        End Try

    End Sub

    Private Sub TaskStatusText_SelectedIndexChanged(sender As Object, e As EventArgs) Handles TaskStatusText.SelectedIndexChanged, TaskTypeCombo.SelectedIndexChanged
        Try
            Dim UserID As String
            Dim row2 As Object = LookUpEdit1.Properties.GetDataSourceRowByKeyValue(LookUpEdit1.EditValue)
            UserID = TryCast(row2, DataRowView)("userid").ToString()

            LoadData(UserID, CStr(TaskMonthText.Text), Me.TaskStatusText.Text, TaskTypeCombo.Text)
        Catch ex As Exception

        End Try
    End Sub

    Private Sub SimpleButton2_Click(sender As Object, e As EventArgs) Handles SimpleButton2.Click
        GridView1.ActiveFilter.Clear()
        Dim TodayString As String = Format(Today, "yyyy-MM-dd")
        GridView1.ActiveFilter.NonColumnFilter = "[AccrualDate] Between (#" & TodayString & "#, #" & TodayString & "#) "

    End Sub

    Private Sub GridControl1_Click(sender As Object, e As EventArgs) Handles GridControl1.Click
        '  Dim aa As String = Me.GridView1.GetRowCellValue(e)
    End Sub

    Private Sub RepositoryItemButtonEdit4_ButtonClick(sender As Object, e As DevExpress.XtraEditors.Controls.ButtonPressedEventArgs) Handles RepositoryItemButtonEdit4.ButtonClick
        'MsgBox("سيتم ارسال مسج للزبون")
        'Me.AlertControl1.Show(Me, "مهام اليوم:", "تحصيل الزيون الهدى")

        Dim strDate As String = Date.Now.ToString("yyyy-MM-dd HH:mm:ss.000")

        '      MsgBox(CloseDate.ToString)
        Dim CustName As String = CType(Me.GridView1.GetRowCellValue(GridView1.FocusedRowHandle, "CustomerName"), String)
        Dim ACCNAME As String = "هل تم تحصيل الزبون :   " & CustName
        Dim result As DialogResult = DevExpress.XtraEditors.XtraMessageBox.Show(ACCNAME, "تأكيد", MessageBoxButtons.YesNo)

        If result = System.Windows.Forms.DialogResult.Yes Then

            AddEvents("تنبيه", "  تم تحصيل الزبون " & " " & CustName, Me.Text, "1800013", My.Settings.UserName, "True")
            AddEvents("تنبيه", "  تم تحصيل الزبون " & " " & CustName, Me.Text, "1800102", My.Settings.UserName, "True")
            AddEvents("تنبيه", "  تم تحصيل الزبون " & " " & CustName, Me.Text, "1800666", My.Settings.UserName, "True")

            Try
                Dim TaskID As String = CType(Me.GridView1.GetRowCellValue(GridView1.FocusedRowHandle, "TaskID"), String)

                Dim sql As New SQLControl
                Dim SQLUpdateStatus As String = "Update [CRM].[dbo].[CRMTasks]  set [NoteStatus] ='تم التحصيل' , CloseNote='تم التحصيل' where [TaskID]= " & TaskID
                sql.CRMRunQuery(SQLUpdateStatus)

                Dim sql2 As New SQLControl
                Dim SQLUpdateDate As String = "Update [CRM].[dbo].[CRMTasks]  set [CloseDate] = CONVERT(DATETIME, '" & strDate & "', 102) where [TaskID]= " & TaskID
                sql2.CRMRunQuery(SQLUpdateDate)

                If CType(Global.DevExpress.XtraEditors.XtraMessageBox.Show(CType("تم تحصيل واغلاق المهمة، هل تريد ارسال رسالة الى المحصل", String), CType("تأكيد", String), CType(Global.System.Windows.Forms.MessageBoxButtons.YesNo, Global.System.Windows.Forms.MessageBoxButtons)), Global.System.Windows.Forms.DialogResult) = Global.System.Windows.Forms.DialogResult.Yes Then
                    Dim msg As String = DevExpress.XtraEditors.XtraInputBox.Show("ملاحظة المحصل", " ادخل ملاحظات للمحصل حول دفعة الزبون", "")
                    FunSendSmS2(Me.MobileText.Text, "شيك جاهز" & " " & CustName & " " & msg & " :" & My.Settings.UserName)
                Else
                    MsgBox("لم يتم ارسال رسالة")
                End If
                '   InsertLogs(CInt(TaskID), My.Settings.UserName, "type", "تحصيل")
                SqlDataSource1.Fill()
            Catch ex As Exception

            End Try

            Dim UserID As String
            Dim row2 As Object = LookUpEdit1.Properties.GetDataSourceRowByKeyValue(LookUpEdit1.EditValue)
            UserID = TryCast(row2, DataRowView)("userid").ToString()
            LoadData(UserID, CStr(Me.TaskMonthText.Text), Me.TaskStatusText.Text, Me.TaskTypeCombo.Text)
        Else
            Exit Sub
        End If

    End Sub

    Private Sub AlertControl1_BeforeFormShow(ByVal sender As System.Object,
ByVal e As DevExpress.XtraBars.Alerter.AlertFormEventArgs) Handles AlertControl1.BeforeFormShow
        e.AlertForm.OpacityLevel = 1
    End Sub

    Private Sub AlertControl1_ButtonClick(sender As Object, e As AlertButtonClickEventArgs) Handles AlertControl1.ButtonClick
        If e.ButtonName = "EDITDATE" Then
            MsgBox("تاجيل")
        End If
        If e.ButtonName = "Tahsel" Then
            MsgBox("تحصيل")
        End If
    End Sub

    Private Sub GridView1_CustomDrawRowIndicator(sender As Object, e As DevExpress.XtraGrid.Views.Grid.RowIndicatorCustomDrawEventArgs) Handles GridView1.CustomDrawRowIndicator
        Dim gw As GridView = TryCast(sender, GridView)
        If e.RowHandle >= 0 Then
            e.Info.DisplayText = (e.RowHandle + 1).ToString
        End If
    End Sub

    Private Sub SimpleButton3_Click(sender As Object, e As EventArgs) Handles ButtonStop.Click

        Try
            If GridView1.RowCount = 0 Then MsgBox("لا يوجد مهام") : Exit Sub
            Dim CustCount As String = CStr(GridView1.RowCount - 1)
            If CInt(GetSMSBalance()) < CInt(CustCount) Then MsgBox("لا يوجد رصيد كافي") : Exit Sub
            Dim result As DialogResult = DevExpress.XtraEditors.XtraMessageBox.Show("  هل تريد ارسال مسجات تحذير عدد:   " & CustCount, "تأكيد", MessageBoxButtons.YesNo)

            If result = System.Windows.Forms.DialogResult.Yes Then
                Dim AcNo, SentNo As Integer
                For AcNo = 0 To GridView1.RowCount - 1
                    Dim CusID As String = CType(GridView1.GetRowCellValue(AcNo, "CustID"), String)
                    Dim CustNo As String = GetAccData(CusID).sphone
                    Dim TaskID As Integer = CType(GridView1.GetRowCellValue(AcNo, "TaskID"), Integer)
                    If CustNo <> "" Then
                        SendAlertMessage(TaskID, FunSendSmS2(CustNo, My.Settings.StopMessage))
                    End If
                Next

                Dim sql As New SQLControl
                Dim i As Integer
                Dim SQLUpdateStatus As String = "select count(TaskID) as SentCount from [CRM].[dbo].[CRMTasks]
                                                 where TaskMonth  ='" & CStr(TaskMonthText.EditValue) & "' and [AlertMessage] = 'Message Sent Successfully!'
                                                 and ToUser='" & CStr(LookUpEdit1.EditValue) & "'"
                sql.CRMRunQuery(SQLUpdateStatus)
                If Not IsDBNull(sql.SQLDS.Tables(0).Rows(i).Item("SentCount")) Then SentNo = CInt(sql.SQLDS.Tables(0).Rows(i).Item("SentCount"))

                DevExpress.XtraEditors.XtraMessageBox.Show("تم ارسال " + CType(SentNo, String) + " " + "زبون")

                Dim aa2 As String = ""
                Dim row2 As Object = LookUpEdit1.Properties.GetDataSourceRowByKeyValue(LookUpEdit1.EditValue)
                aa2 = TryCast(row2, DataRowView)("userid").ToString()
                LoadData(aa2, TaskMonthText.Text, TaskStatusText.Text, TaskTypeCombo.Text)

                ColAlertMessage.Visible = True

            End If
        Catch ex As Exception
            MsgBox("Error")
        End Try

    End Sub

    Sub SendAlertMessage(TaskIdAlert As Integer, Result As String)
        Dim sql As New SQLControl
        Dim SQLUpdateStatus As String = "Update [CRM].[dbo].[CRMTasks]  set [AlertMessage] ='" & Result & "' ,AlertMessageDateTime = GETDATE()    where [TaskID]= " & TaskIdAlert
        sql.CRMRunQuery(SQLUpdateStatus)

    End Sub
    Sub SendBalanceMessage(TaskIdAlert As Integer, Result As String, SMSString As String)
        Dim sql As New SQLControl
        Dim SQLUpdateStatus As String = "Update [CRM].[dbo].[CRMTasks]  set [BalanceMessage] ='" & Result & "' ,BalanceMessageDateTime = GETDATE() ,BalanceMessageTEXT= '" & SMSString & "'   where [TaskID]= " & TaskIdAlert
        sql.CRMRunQuery(SQLUpdateStatus)

    End Sub

    Private Sub SimpleButton4_Click(sender As Object, e As EventArgs) Handles ButtonAlarm.Click
        Try
            If GridView1.RowCount = 0 Then MsgBox("لا يوجد مهام") : Exit Sub
            Dim CustCount As String = CStr(GridView1.RowCount - 1)
            If CInt(GetSMSBalance()) < CInt(CustCount) Then MsgBox("لا يوجد رصيد كافي") : Exit Sub
            Dim result As DialogResult = DevExpress.XtraEditors.XtraMessageBox.Show("  هل تريد ارسال مسجات تحذير عدد:   " & CustCount, "تأكيد", MessageBoxButtons.YesNo)

            If result = System.Windows.Forms.DialogResult.Yes Then
                Dim AcNo, SentNo As Integer
                For AcNo = 0 To GridView1.RowCount - 1
                    Dim CusID As String = CType(GridView1.GetRowCellValue(AcNo, "CustID"), String)
                    Dim CustNo As String = GetAccData(CusID).sphone
                    Dim TaskID As Integer = CType(GridView1.GetRowCellValue(AcNo, "TaskID"), Integer)
                    If CustNo <> "" Then
                        SendAlertMessage(TaskID, FunSendSmS2(CustNo, My.Settings.AlertMessage))
                    End If
                Next

                Dim sql As New SQLControl
                Dim i As Integer
                Dim SQLUpdateStatus As String = "select count(TaskID) as SentCount from [CRM].[dbo].[CRMTasks]
                                                 where TaskMonth  ='" & CStr(TaskMonthText.EditValue) & "' and [AlertMessage] = 'Message Sent Successfully!'
                                                 and ToUser='" & CStr(LookUpEdit1.EditValue) & "'"
                sql.CRMRunQuery(SQLUpdateStatus)
                If Not IsDBNull(sql.SQLDS.Tables(0).Rows(i).Item("SentCount")) Then SentNo = CInt(sql.SQLDS.Tables(0).Rows(i).Item("SentCount"))

                DevExpress.XtraEditors.XtraMessageBox.Show("تم ارسال " + CType(SentNo, String) + " " + "زبون")

                Dim aa2 As String = ""
                Dim row2 As Object = LookUpEdit1.Properties.GetDataSourceRowByKeyValue(LookUpEdit1.EditValue)
                aa2 = TryCast(row2, DataRowView)("userid").ToString()
                LoadData(aa2, TaskMonthText.Text, TaskStatusText.Text, TaskTypeCombo.Text)

                ColAlertMessage.Visible = True

            End If
        Catch ex As Exception
            MsgBox("Error")
        End Try
    End Sub

    Private Sub SimpleButton5_Click(sender As Object, e As EventArgs) Handles SimpleButton5.Click
        My.Forms.CRMAlarmMessages.ComboBoxEdit1.Text = "رسالة تحذير"
        CRMAlarmMessages.Show()
    End Sub

    Private Sub SimpleButton6_Click(sender As Object, e As EventArgs) Handles SimpleButton6.Click
        My.Forms.CRMAlarmMessages.ComboBoxEdit1.Text = "رسالة ايقاف"
        CRMAlarmMessages.Show()
    End Sub

    Private Sub SimpleButton7_Click(sender As Object, e As EventArgs) Handles SimpleButton7.Click
        GridControl1.ShowPrintPreview()




    End Sub

    Private Sub RepositoryItemButtonEdit1_Click(sender As Object, e As EventArgs)

    End Sub

    Private Sub RepositoryItemButtonEdit5_ButtonClick(sender As Object, e As DevExpress.XtraEditors.Controls.ButtonPressedEventArgs)

        Dim strDate As String = Date.Now.ToString("yyyy-MM-dd HH:mm:ss.000")

        '      MsgBox(CloseDate.ToString)
        Dim CustName As String = CType(Me.GridView1.GetRowCellValue(GridView1.FocusedRowHandle, "CustomerName"), String)
        Dim ACCNAME As String = "هل تم تحصيل الزبون :   " & CustName
        Dim result As DialogResult = DevExpress.XtraEditors.XtraMessageBox.Show(ACCNAME, "تأكيد", MessageBoxButtons.YesNo)

        If result = System.Windows.Forms.DialogResult.Yes Then
            '      Try

            AddEvents("تنبيه", "  تم تحصيل الزبون " & " " & CustName, Me.Text, "1800013", My.Settings.UserName, "True")
            AddEvents("تنبيه", "  تم تحصيل الزبون " & " " & CustName, Me.Text, "1800013", My.Settings.UserName, "True")
            AddEvents("تنبيه", "  تم تحصيل الزبون " & " " & CustName, Me.Text, "1800013", My.Settings.UserName, "True")

            Dim TaskID As String = CType(Me.GridView1.GetRowCellValue(GridView1.FocusedRowHandle, "TaskID"), String)

            Dim sql As New SQLControl
            Dim SQLUpdateStatus As String = "Update [CRM].[dbo].[CRMTasks]  set [NoteStatus] ='تم التحصيل' , CloseNote='تم التحصيل' where [TaskID]= " & TaskID
            sql.CRMRunQuery(SQLUpdateStatus)

            Dim sql2 As New SQLControl
            Dim SQLUpdateDate As String = "Update [CRM].[dbo].[CRMTasks]  set [CloseDate] = CONVERT(DATETIME, '" & strDate & "', 102) where [TaskID]= " & TaskID
            sql2.CRMRunQuery(SQLUpdateDate)

            '   InsertLogs(CInt(TaskID), My.Settings.UserName, "", "تحصيل")

            If CType(Global.DevExpress.XtraEditors.XtraMessageBox.Show(CType("تم تحصيل واغلاق المهمة، هل تريد ارسال رسالة الى المحصل", String), CType("تأكيد", String), CType(Global.System.Windows.Forms.MessageBoxButtons.YesNo, Global.System.Windows.Forms.MessageBoxButtons)), Global.System.Windows.Forms.DialogResult) = Global.System.Windows.Forms.DialogResult.Yes Then
                Dim msg As String = DevExpress.XtraEditors.XtraInputBox.Show("ملاحظة المحصل", " ادخل ملاحظات للمحصل حول دفعة الزبون", "")
                FunSendSmS2(Me.MobileText.Text, "شيك جاهز" & " " & CustName & " " & msg & " :" & My.Settings.UserName)
            Else
                MsgBox("لم يتم ارسال رسالة")
            End If

            SqlDataSource1.Fill()
            LoadData(My.Settings.UserName, CStr(Me.TaskMonthText.Text), Me.TaskStatusText.Text, Me.TaskTypeCombo.Text)
            '  Catch ex As Exception

            '   End Try
        Else
            Exit Sub
        End If

    End Sub

    'Private Sub InsertLogs(TaskID As Integer, User As String, TaskType As String, TaskLogType As String)
    '    Dim sql As New SQLControl
    '    Dim SQLInsertTaskLog As String = " insert into  [CRM].[dbo].[CRMTasksLogs]  set
    '                                       [TaskID] = " & TaskID & ", " & "
    '                                       [TaskType]= " & TaskType & ", " & "
    '                                       [TaskLogDate] = " & "'" & Today.ToString & "', " & "
    '                                       [TaskLogType] = " & "'" & TaskLogType & "', " & "
    '                                       [TaskLogUser] = " & "'" & TaskLogType & "', " & "
    '                                       [TaskLogTime] = " & "'" & Now.ToShortTimeString & "' "
    '    MsgBox(SQLInsertTaskLog)
    '    sql.CRMRunQuery(SQLInsertTaskLog)
    'End Sub

    Public Sub CreatTableSummery()
        ' Declare DataTable
        Dim Table1 As DataTable = New DataTable
        ' Define columns
        Table1.Columns.Add("Summery", GetType(System.String))
        Table1.Columns.Add("Values", GetType(System.Int32))

        ' Add a row of data
        '     Table1.Rows.Add("المهام", TextEdit3.EditValue)
        Table1.Rows.Add("المحصلة", TextEdit2.EditValue)
        Table1.Rows.Add("المغلقة", TextEdit5.EditValue)
        Table1.Rows.Add("المتبقية", AllTasksText.EditValue)

        '  ChartControl1.DataSource = Table1

        '     Try

        ChartControl1.DataSource = Table1
        '''    ChartControl1.SeriesDataMember = "Summery"
        '''     ChartControl1.SeriesTemplate.ArgumentDataMember = "Summery"

        '''     ChartControl1.SeriesTemplate.ValueDataMembers.AddRange(New String() {"Values"})

        '''    ChartControl1.SeriesTemplate.View = New DevExpress.XtraCharts.StackedBarSeriesView()
        '  ChartControl1.SeriesTemplate.View = New DevExpress.XtraCharts.StackedBarSeriesView()

        '''   ChartControl1.SeriesNameTemplate.BeginText = "Summery: "

        'Dim label As DevExpress.XtraCharts.SideBySideBarSeriesLabel = TryCast(ChartControl1.Series(0).Label, DevExpress.XtraCharts.SideBySideBarSeriesLabel)
        'If label IsNot Nothing Then
        '    label.Position = DevExpress.XtraCharts.BarSeriesLabelPosition.Top
        'End If
        '  Catch ex As Exception
        '  MsgBox("لا يوجد بيانات")
        '  End Try

    End Sub

    Private Sub CraetMonthlyChart(fleet As String)

    End Sub

    Private Sub SimpleButton8_Click(sender As Object, e As EventArgs)
        MsgBox(SqlDataSource1.Queries("CRMTasksAll").ToString)
    End Sub

    'Private Sub gridView_CustomDrawCell(ByVal sender As Object, ByVal e As DevExpress.XtraGrid.Views.Base.RowCellCustomDrawEventArgs)
    '    Dim view As GridView = TryCast(sender, GridView)
    '    If e.RowHandle = view.FocusedRowHandle Then Return
    '    If e.Column.FieldName <> "AlertMessage" Then Return
    '    '   If Convert.ToInt32(e.CellValue) > 30 Then e.Appearance.BackColor = Color.FromArgb(60, Color.Salmon)
    '    e.DefaultDraw()
    '    Dim discount As String = Convert.ToString(view.GetRowCellValue(e.RowHandle, view.Columns("AlertMessage")))
    '    Dim image As Image = Image.FromFile("‪E:\Messaging-Sent-icon.png")
    '    If discount IsNot Nothing Then e.Graphics.DrawImage(image, e.Bounds.Location)

    'End Sub

    Private Sub GridView1_CustomDrawCell(ByVal sender As Object,
ByVal e As RowCellCustomDrawEventArgs) Handles GridView1.CustomDrawCell

        Dim ImageSent As Image = My.Resources.Sent
        Dim ImageFalse As Image = DevExpress.Images.ImageResourceCache.Default.GetImage("images/actions/close_16x16.png")
        Dim View As GridView = CType(sender, GridView)
        Dim ImageDelete As Image = DevExpress.Images.ImageResourceCache.Default.GetImage("images/communication/phone_16x16.png")
        Dim EmptyPhone As Image = DevExpress.Images.ImageResourceCache.Default.GetImage("images/support/info_16x16.png")

        If e.Column.FieldName = "AlertMessage" Then
            Dim category As String = View.GetRowCellDisplayText(e.RowHandle, View.Columns("AlertMessage"))
            If category = "Message Sent Successfully!" Then
                e.Graphics.DrawImage(ImageSent, e.Bounds.Location)
                e.DisplayText = "تم"
            End If
            If category = "H006|Invalid Recipient Number" Then
                e.Graphics.DrawImage(ImageFalse, e.Bounds.Location)
                e.DisplayText = "خطا بالرقم"
            End If
            If category = "" Then
                ' e.Graphics.DrawImage(ImageDelete, e.Bounds.Location)
                e.DisplayText = ""
            End If
        End If

        If e.Column.FieldName = "Mobile" Then
            Dim category As String = View.GetRowCellDisplayText(e.RowHandle, View.Columns("Mobile"))
            If category <> "" Then
                e.Graphics.DrawImage(ImageDelete, e.Bounds.Location)
            Else
                e.Graphics.DrawImage(EmptyPhone, e.Bounds.Location)
                e.DisplayText = "فارغ"
            End If
        End If

    End Sub

    Private Sub SimpleButton9_Click(sender As Object, e As EventArgs) Handles SimpleButton9.Click

    End Sub

    Private Sub TileBarItem2_ItemClick(sender As Object, e As DevExpress.XtraEditors.TileItemEventArgs) Handles TileBarItem2.ItemClick
        GridView1.ActiveFilter.Clear()
        Dim TodayString As String = Format(Today, "yyyy-MM-dd")
        GridView1.ActiveFilter.NonColumnFilter = "[AccrualDate] Between (#" & TodayString & "#, #" & TodayString & "#) "
    End Sub

    Private Sub TileBarItem5_ItemClick(sender As Object, e As DevExpress.XtraEditors.TileItemEventArgs) Handles TileBarItem5.ItemClick
        GridControl1.ShowPrintPreview()
    End Sub

    Private Sub GetImage()
        Dim sql As New SQLControl
        Dim i As Integer
        Dim SQLString As String = " SELECT picture  " &
                                  " FROM    employeesdata" &
                                  " where  empid= '" & My.Settings.UserName & "'"
        sql.CRMRunQuery(SQLString)

        If sql.SQLDS.Tables(0).Rows(i).Item("picture").ToString <> "" Then
            Dim bytes As [Byte]() = CType(sql.SQLDS.Tables(0).Rows(i).Item("picture"), Byte())
            Dim ms As New IO.MemoryStream(bytes)
            PictureEdit1.Image = Image.FromStream(ms)
        End If
    End Sub

    Private Sub PanelControl3_Paint(sender As Object, e As PaintEventArgs) Handles PanelControl3.Paint

    End Sub

    Private Sub SimpleButton3_Click_1(sender As Object, e As EventArgs) Handles SimpleButton3.Click

        Try

            If GridView1.RowCount = 0 Then MsgBox("لا يوجد مهام") : Exit Sub
            Dim CustCount As String = CStr(GridView1.RowCount - 1)
            If CInt(GetSMSBalance()) < CInt(CustCount) Then MsgBox("لا يوجد رصيد كافي") : Exit Sub
            Dim result As DialogResult = DevExpress.XtraEditors.XtraMessageBox.Show("  هل تريد ارسال مسجات  عدد:   " & CustCount, "تأكيد", MessageBoxButtons.YesNo)
            If result = System.Windows.Forms.DialogResult.Yes Then
                Dim AcNo As Integer = 0, SentNo As Integer = 0
                Dim MonthString As Integer = CInt(Mid(TaskMonthText.Text, 5, 2))
                Dim YearString As Integer = CInt(Mid(TaskMonthText.Text, 1, 4))
                For AcNo = 0 To GridView1.RowCount - 1
                    Dim CusID As String = CType(GridView1.GetRowCellValue(AcNo, "CustID"), String)
                    Dim CustName As String = CType(GridView1.GetRowCellValue(AcNo, "CustomerName"), String)

                    Dim CustDebit As Decimal = GetDebitBalance(CusID, YearString, MonthString)
                    Dim Msg As String = " يسرنا ابلاغكم بأن سحوبات شهر   " & MonthString & "/" & YearString & " بلغت " & CStr(CustDebit) & " NIS " & " للاستفسار يرجى الاتصال على رقم 022222222 "
                    Dim CustMobile As String = GetAccData(CusID).sphone
                    Dim TaskID As Integer = CType(GridView1.GetRowCellValue(AcNo, "TaskID"), Integer)

                    If Not String.IsNullOrEmpty(CustMobile) And CustDebit > 10 Then
                        SendBalanceMessage(TaskID, FunSendSmS2(CustMobile, Msg), Msg)
                    End If

                Next

                Dim sql As New SQLControl
                Dim i As Integer
                Dim SQLUpdateStatus As String = "select count(TaskID) as SentCount from [CRM].[dbo].[CRMTasks]
                                                 where TaskMonth  ='" & CStr(TaskMonthText.EditValue) & "' and [BalanceMessage] = 'Message Sent Successfully!'
                                                 and ToUser='" & CStr(LookUpEdit1.EditValue) & "'"
                sql.CRMRunQuery(SQLUpdateStatus)
                If Not IsDBNull(sql.SQLDS.Tables(0).Rows(i).Item("SentCount")) Then SentNo = CInt(sql.SQLDS.Tables(0).Rows(i).Item("SentCount"))

                DevExpress.XtraEditors.XtraMessageBox.Show("تم ارسال " + CType(SentNo, String) + " " + "زبون")

                Dim aa2 As String = ""
                Dim row2 As Object = LookUpEdit1.Properties.GetDataSourceRowByKeyValue(LookUpEdit1.EditValue)
                aa2 = TryCast(row2, DataRowView)("userid").ToString()
                LoadData(aa2, TaskMonthText.Text, TaskStatusText.Text, TaskTypeCombo.Text)

                ColAlertMessage.Visible = True

            End If
        Catch ex As Exception
            MsgBox("Error")
        End Try

    End Sub

    Private Sub RepositorySendSMS_ButtonClick(sender As Object, e As DevExpress.XtraEditors.Controls.ButtonPressedEventArgs) Handles RepositorySendSMS.ButtonClick
        Dim CustMobile As String = CType(Me.GridView1.GetRowCellValue(GridView1.FocusedRowHandle, "Mobile"), String)
        My.Forms.CRMSendSMSMessages.TextMobileNo.Text = CustMobile
        My.Forms.CRMSendSMSMessages.MemoEdit1.Select()
        CRMSendSMSMessages.Show()
    End Sub
End Class