Public Class CustomersOrders
    Sub New()

        InitializeComponent()
        ' This line of code is generated by Data Source Configuration Wizard
        ' Fill a SqlDataSource
        SqlDataSource1.Fill()
    End Sub

    Private Sub CustomersOrders_Load(sender As Object, e As EventArgs) Handles MyBase.Load
        GridView1.BestFitColumns()
    End Sub

    Private Sub SimpleButton1_Click(sender As Object, e As EventArgs) Handles SimpleButton1.Click
        '     My.Forms.CustomersOrdersAdd.CRMCustomersOrdersTableAdapter.FillByID(My.Forms.CustomersOrdersAdd.CRMDataSet.CRMCustomersOrders, CType(-1, Integer))
        '    My.Forms.CustomersOrdersAdd.IDTextBox.Text = CStr(-1)


        My.Forms.CustomersOrdersAdd.CRMCustomersOrdersBindingSource.AddNew()
        CustomersOrdersAdd.Show()
        My.Forms.CustomersOrdersAdd.OrderStatusTextBox.Text = "جديد"
        My.Forms.CustomersOrdersAdd.RecDateDateEdit.DateTime = Today
    End Sub

    Private Sub SimpleButton2_Click(sender As Object, e As EventArgs) Handles SimpleButton2.Click
        SqlDataSource1.Fill()
        GridView1.BestFitColumns()
    End Sub

    Private Sub GridControl1_Click(sender As Object, e As EventArgs) Handles GridControl1.DoubleClick
        My.Forms.CustomersOrdersAdd.IDTextBox.Select()
        Dim OrderId As Integer = CInt(GridView1.GetRowCellValue(GridView1.FocusedRowHandle, "OrderID"))
        '   My.Forms.CustomersOrdersAdd.CRMCustomersOrdersTableAdapter.FillByID(My.Forms.CustomersOrdersAdd.CRMDataSet.CRMCustomersOrders, CType(OrderId, Integer))
        My.Forms.CustomersOrdersAdd.IDTextBox.Text = CStr(OrderId)
        My.Forms.CustomersOrdersAdd.CustNameTextBox.Select()
        CustomersOrdersAdd.Show()
    End Sub

 

    Private Sub SimpleButton3_Click(sender As Object, e As EventArgs) Handles SimpleButton3.Click
        GridControl1.ShowPrintPreview()
    End Sub
End Class