Imports System
Imports System.Collections.Generic
Imports System.Linq
Imports System.Text
Imports System.Threading.Tasks
Imports DevExpress.DataAccess
Imports DevExpress.DashboardCommon

Namespace Win_Dashboards
    Partial Public Class OrpakSalesByStationMonthly
        Inherits DevExpress.DashboardCommon.Dashboard
        Public Sub New()
            InitializeComponent()
            '  This line of code is generated by Data Source Configuration Wizard
            '  TransactionsTableAdapter1.Fill(HO_DATADataSet1.transactions)
            '  This line of code is generated by Data Source Configuration Wizard
            '  TransactionsTableAdapter2.Fpill(HO_DATADataSet2.transactions)
            '  This line of code is generated by Data Source Configuration Wizard
            '  TransactionsTableAdapter3.Fill(HO_DATADataSet3.transactions)
            '   Me.DashboardSqlDataSource1.Queries("Query").Parameters(0).Value = "2017-12-31"
            '    Me.DashboardSqlDataSource1.Queries("Query").Parameters(1).Value = "2020-12-31"


        End Sub
    End Class
End Namespace