Imports System
Imports System.Collections.Generic
Imports System.Linq
Imports System.Text
Imports System.Threading.Tasks
Imports DevExpress.DataAccess
Imports DevExpress.DashboardCommon

Namespace Win_Dashboards
    Partial Public Class OrpakSles
        Inherits DevExpress.DashboardCommon.Dashboard
        Public Sub New()
            InitializeComponent()
            ' This line of code is generated by Data Source Configuration Wizard
            '   TransactionsTableAdapter1.Fill(HO_DATADataSet1.transactions)
        End Sub
    End Class
End Namespace