Imports System.Drawing.Printing
Imports DevExpress.XtraPrinting
Imports DevExpress.XtraGrid.Views.Base
Imports DevExpress.XtraGrid.Views.Grid

Public Class OrpakCardsAll

    Sub New()

        InitializeComponent()
        ' This line of code is generated by Data Source Configuration Wizard
        ' Fill a SqlDataSource
        SqlDataSource1.Fill()
    End Sub

    Private Sub SimpleButton1_Click(sender As Object, e As EventArgs) Handles SimpleButton1.Click
        If Not GridControl1.IsPrintingAvailable Then
            MessageBox.Show("The 'DevExpress.XtraPrinting' library is not found", "Error")
            Return
        End If

        Dim link As New PrintableComponentLink(New PrintingSystem())
        link.Component = GridControl1
        link.Landscape = True
        link.Margins.Left = 10
        link.Margins.Right = 10
        link.Margins.Top = 10
        link.Margins.Bottom = 10
        link.ShowPreview()

    End Sub

    Private Sub GridView1_CustomDrawCell(ByVal sender As Object,
  ByVal e As RowCellCustomDrawEventArgs) Handles GridView1.CustomDrawCell
        'Dim ImageTrue As Image = Image.FromFile(Application.StartupPath + "\..\..\" + "true.jpg")
        'Dim ImageFalse As Image = Image.FromFile(Application.StartupPath + "\..\..\" + "false.jpg")
        'Dim ImageDelete As Image = Image.FromFile(Application.StartupPath + "\..\..\" + "Delete.jpg")
        Dim View As GridView = CType(sender, GridView)
        If e.Column.FieldName = "status" Then
            Dim category As String = View.GetRowCellDisplayText(e.RowHandle, View.Columns("status"))
            If category = "1" Then
                '    e.Graphics.DrawImage(ImageFalse, e.Bounds.Location)
                e.DisplayText = "موقوفة"
            End If
            If category = "2" Then
                '  e.Graphics.DrawImage(ImageTrue, e.Bounds.Location)
                e.DisplayText = "فعالة"
            End If
            If category = "0" Then
                '  e.Graphics.DrawImage(ImageDelete, e.Bounds.Location)
                e.DisplayText = "محذوفة"
            End If
        End If

    End Sub

    Private Sub GridControl1_Click(sender As Object, e As EventArgs) Handles GridControl1.Click

    End Sub

    Private Sub PanelControl1_Paint(sender As Object, e As PaintEventArgs) Handles PanelControl1.Paint

    End Sub

    Private Sub OrpakCardsAll_Load(sender As Object, e As EventArgs) Handles MyBase.Load

    End Sub

End Class