Imports System.Text
Imports System.Timers
Imports DevExpress.DataAccess
Imports DevExpress.DataAccess.Sql
Imports DevExpress.XtraCharts

Public Class OrpakStationSales
    Dim chartTitle1 As New ChartTitle()
    Dim chartTitle2 As New ChartTitle()
    Sub New()

        InitializeComponent()
        ' This line of code is generated by Data Source Configuration Wizard
        ' Fill a SqlDataSource
        '   SqlDataSource1.Queries(0).Parameters(1).Value = "CSTMR"



        ' This line of code is generated by Data Source Configuration Wizard
        ' Fill a SqlDataSource
        '    SqlDataSource1.Fill()
    End Sub

    Private Sub XtraForm1_Load(sender As Object, e As EventArgs) Handles MyBase.Load
        Dim Timer1 As System.Timers.Timer = New Timer(600000)
        AddHandler Timer1.Elapsed, AddressOf OnTimedEvent
        Timer1.Enabled = True
        CreateChart()
    End Sub
    Private Sub OnTimedEvent(source As Object, e As ElapsedEventArgs)
        FillDataSource()
        ChartControl1.Titles.Clear()
        CreateChart()
    End Sub
    Private Sub CreateChart()


        ' Define the text for the titles.
        chartTitle1.Text = "تقرير المبيعات اليومية"
        chartTitle2.Text = "اخر تحديث" & ": " & Format(Now, "yyyy-MM-dd HH:mm")

        chartTitle2.WordWrap = True
        chartTitle2.MaxLineCount = 2

        ' Define the alignment of the titles.
        chartTitle1.Alignment = StringAlignment.Center
        chartTitle2.Alignment = StringAlignment.Center

        ' Place the titles where it's required.
        chartTitle1.Dock = ChartTitleDockStyle.Top
        chartTitle2.Dock = ChartTitleDockStyle.Top

        ' Customize a title's appearance.
#Disable Warning BC40000 ' Type or member is obsolete
        chartTitle1.Antialiasing = True
#Enable Warning BC40000 ' Type or member is obsolete
        chartTitle1.Font = New Font("Tahoma", 14, FontStyle.Bold)
        chartTitle1.TextColor = Color.Red
        chartTitle1.Indent = 10

#Disable Warning BC40000 ' Type or member is obsolete
        chartTitle2.Antialiasing = True
#Enable Warning BC40000 ' Type or member is obsolete
        chartTitle2.Font = New Font("Tahoma", 10, FontStyle.Bold)
        chartTitle2.TextColor = Color.Blue
        chartTitle2.Indent = 10

        ' Add the titles to the chart.
        ChartControl1.Titles.AddRange(New ChartTitle() {chartTitle1, chartTitle2})
    End Sub

    Private Sub ComboBoxEdit1_SelectedIndexChanged(sender As Object, e As EventArgs) Handles ComboBoxEdit1.SelectedIndexChanged
        FillDataSource()



        'Dim values As String() = New String() {"ATNDT", "CSTMR"}
        'Dim count As Integer = values.Length
        'Dim builder As StringBuilder = New StringBuilder()

        'For i As Integer = 0 To values.Length - 1
        '    builder.Append(String.Format("'{0}'", values(i)))
        '    If i <> count - 1 Then builder.Append(","c)
        'Next

        ''   Dim sqlDs = TryCast((TryCast(sender, XtraReport)).DataSource, SqlDataSource)
        ''   Dim query = sqlDs.Queries.OfType(Of StoredProcQuery)().FirstOrDefault()
        'MsgBox(builder.ToString())
        'SqlDataSource1.Queries(0).Parameters(1).Value = builder.ToString()

    End Sub
    Private Sub FillDataSource()
        SqlDataSource1.Queries(0).Parameters(1).Value = ComboBoxEdit1.Text
        SqlDataSource1.Fill()
    End Sub

End Class