Public Class OrpakTransactions

    Sub New()

        InitializeComponent()
        ' This line of code is generated by Data Source Configuration Wizard
        '     TransactionsTableAdapter1.Fill(HO_DATADataSet1.transactions)
        ' This line of code is generated by Data Source Configuration Wizard
        ' Fill a SqlDataSource
        '   SqlDataSource1.Fill()
    End Sub

    Private Sub OrpakTransactions_Load(sender As Object, e As EventArgs) Handles MyBase.Load

    End Sub

    Private Sub SimpleButton1_Click(sender As Object, e As EventArgs) Handles SimpleButton1.Click

        SqlDataSource1.Queries(0).Parameters(0).Value = Format(DateTimePicker1.Value, "MM/dd/yyyy")
        SqlDataSource1.Queries(0).Parameters(1).Value = Format(DateTimePicker2.Value, "MM/dd/yyyy")
        SqlDataSource1.Fill()
    End Sub

    Private Sub SimpleButton2_Click(sender As Object, e As EventArgs) Handles SimpleButton2.Click
        GridControl1.ShowPrintPreview()
    End Sub

End Class